GET localhost:9000/api/locations


###
POST localhost:9000/api/users
Content-Type: application/json

{
  "email": "first.last@email.com",
  "password": "pass",
  "firstName": "First Name",
  "lastName": "Last Name"
}

###
POST localhost:9000/api/users/login
Content-Type: application/json

{
  "email": "first.last@email.com",
  "password": "pass"
}

> {%
    client.global.set("authToken", response.body.authToken)
%}


###
GET localhost:9000/api/user
Authorization: Bearer {{authToken}}


###
PUT localhost:9000/api/user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "first.last@email.com",
  "password": "pass",
  "firstName": "F",
  "lastName": "Last Name"
}