CREATE TABLE location (
    id    BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    state varchar,
    city  VARCHAR,
    label VARCHAR NOT NULL,
    CONSTRAINT city_should_have_state CHECK (state IS NOT NULL OR city IS NULL),
    CONSTRAINT unique_state_city UNIQUE (state, city) -- Add "NULLS NOT DISTINCT" in Postgres 15
);

INSERT INTO location(state, city, label)
VALUES (NULL, NULL, 'United States'),
    ('AL', NULL, 'Alabama'),
    ('AK', NULL, 'Alaska'),
    ('AZ', NULL, 'Arizona'),
    ('AR', NULL, 'Arkansas'),
    ('CA', NULL, 'California'),
    ('CO', NULL, 'Colorado'),
    ('CT', NULL, 'Connecticut'),
    ('DE', NULL, 'Delaware'),
    ('DC', NULL, 'District of Columbia'),
    ('FL', NULL, 'Florida'),
    ('GA', NULL, 'Georgia'),
    ('HI', NULL, 'Hawaii'),
    ('ID', NULL, 'Idaho'),
    ('IL', NULL, 'Illinois'),
    ('IN', NULL, 'Indiana'),
    ('IA', NULL, 'Iowa'),
    ('KS', NULL, 'Kansas'),
    ('KY', NULL, 'Kentucky'),
    ('LA', NULL, 'Louisiana'),
    ('ME', NULL, 'Maine'),
    ('MD', NULL, 'Maryland'),
    ('MA', NULL, 'Massachusetts'),
    ('MI', NULL, 'Michigan'),
    ('MN', NULL, 'Minnesota'),
    ('MS', NULL, 'Mississippi'),
    ('MO', NULL, 'Missouri'),
    ('MT', NULL, 'Montana'),
    ('NE', NULL, 'Nebraska'),
    ('NV', NULL, 'Nevada'),
    ('NH', NULL, 'New Hampshire'),
    ('NJ', NULL, 'New Jersey'),
    ('NM', NULL, 'New Mexico'),
    ('NY', NULL, 'New York'),
    ('NC', NULL, 'North Carolina'),
    ('ND', NULL, 'North Dakota'),
    ('OH', NULL, 'Ohio'),
    ('OK', NULL, 'Oklahoma'),
    ('OR', NULL, 'Oregon'),
    ('PA', NULL, 'Pennsylvania'),
    ('RI', NULL, 'Rhode Island'),
    ('SC', NULL, 'South Carolina'),
    ('SD', NULL, 'South Dakota'),
    ('TN', NULL, 'Tennessee'),
    ('TX', NULL, 'Texas'),
    ('UT', NULL, 'Utah'),
    ('VT', NULL, 'Vermont'),
    ('VA', NULL, 'Virginia'),
    ('WA', NULL, 'Washington'),
    ('WV', NULL, 'West Virginia'),
    ('WI', NULL, 'Wisconsin'),
    ('WY', NULL, 'Wyoming'),
    ('IA', 'Ankeny', 'IA / Ankeny'),
    ('UT', 'Bountiful', 'UT / Bountiful'),
    ('NY', 'New York', 'NY / New York'),
    ('CA', 'Los Angeles', 'CA / Los Angeles'),
    ('IL', 'Chicago', 'IL / Chicago'),
    ('TX', 'Houston', 'TX / Houston'),
    ('AZ', 'Phoenix', 'AZ / Phoenix'),
    ('PA', 'Philadelphia', 'PA / Philadelphia'),
    ('TX', 'San Antonio', 'TX / San Antonio'),
    ('CA', 'San Diego', 'CA / San Diego'),
    ('TX', 'Dallas', 'TX / Dallas'),
    ('CA', 'San Jose', 'CA / San Jose'),
    ('TX', 'Austin', 'TX / Austin'),
    ('FL', 'Jacksonville', 'FL / Jacksonville'),
    ('CA', 'San Francisco', 'CA / San Francisco'),
    ('OH', 'Columbus', 'OH / Columbus'),
    ('IN', 'Indianapolis', 'IN / Indianapolis'),
    ('TX', 'Fort Worth', 'TX / Fort Worth'),
    ('NC', 'Charlotte', 'NC / Charlotte'),
    ('WA', 'Seattle', 'WA / Seattle'),
    ('CO', 'Denver', 'CO / Denver'),
    ('TX', 'El Paso', 'TX / El Paso'),
    ('DC', 'Washington', 'DC / Washington'),
    ('MA', 'Boston', 'MA / Boston'),
    ('MI', 'Detroit', 'MI / Detroit'),
    ('TN', 'Nashville-Davidson', 'TN / Nashville-Davidson'),
    ('TN', 'Memphis', 'TN / Memphis'),
    ('OR', 'Portland', 'OR / Portland'),
    ('OK', 'Oklahoma City', 'OK / Oklahoma City'),
    ('NV', 'Las Vegas', 'NV / Las Vegas'),
    ('KY', 'Louisville/Jefferson County', 'KY / Louisville/Jefferson County'),
    ('MD', 'Baltimore', 'MD / Baltimore'),
    ('WI', 'Milwaukee', 'WI / Milwaukee'),
    ('NM', 'Albuquerque', 'NM / Albuquerque'),
    ('AZ', 'Tucson', 'AZ / Tucson'),
    ('CA', 'Fresno', 'CA / Fresno'),
    ('CA', 'Sacramento', 'CA / Sacramento'),
    ('AZ', 'Mesa', 'AZ / Mesa'),
    ('MO', 'Kansas City', 'MO / Kansas City'),
    ('GA', 'Atlanta', 'GA / Atlanta'),
    ('CA', 'Long Beach', 'CA / Long Beach'),
    ('CO', 'Colorado Springs', 'CO / Colorado Springs'),
    ('NC', 'Raleigh', 'NC / Raleigh'),
    ('FL', 'Miami', 'FL / Miami'),
    ('VA', 'Virginia Beach', 'VA / Virginia Beach'),
    ('NE', 'Omaha', 'NE / Omaha'),
    ('CA', 'Oakland', 'CA / Oakland'),
    ('MN', 'Minneapolis', 'MN / Minneapolis'),
    ('OK', 'Tulsa', 'OK / Tulsa'),
    ('TX', 'Arlington', 'TX / Arlington'),
    ('LA', 'New Orleans', 'LA / New Orleans'),
    ('KS', 'Wichita', 'KS / Wichita'),
    ('OH', 'Cleveland', 'OH / Cleveland'),
    ('FL', 'Tampa', 'FL / Tampa'),
    ('CA', 'Bakersfield', 'CA / Bakersfield'),
    ('CO', 'Aurora', 'CO / Aurora'),
    ('HI', 'Honolulu', 'HI / Honolulu'),
    ('CA', 'Anaheim', 'CA / Anaheim'),
    ('CA', 'Santa Ana', 'CA / Santa Ana'),
    ('TX', 'Corpus Christi', 'TX / Corpus Christi'),
    ('CA', 'Riverside', 'CA / Riverside'),
    ('KY', 'Lexington-Fayette', 'KY / Lexington-Fayette'),
    ('MO', 'St. Louis', 'MO / St. Louis'),
    ('CA', 'Stockton', 'CA / Stockton'),
    ('PA', 'Pittsburgh', 'PA / Pittsburgh'),
    ('MN', 'St. Paul', 'MN / St. Paul'),
    ('OH', 'Cincinnati', 'OH / Cincinnati'),
    ('AK', 'Anchorage', 'AK / Anchorage'),
    ('NV', 'Henderson', 'NV / Henderson'),
    ('NC', 'Greensboro', 'NC / Greensboro'),
    ('TX', 'Plano', 'TX / Plano'),
    ('NJ', 'Newark', 'NJ / Newark'),
    ('NE', 'Lincoln', 'NE / Lincoln'),
    ('OH', 'Toledo', 'OH / Toledo'),
    ('FL', 'Orlando', 'FL / Orlando'),
    ('CA', 'Chula Vista', 'CA / Chula Vista'),
    ('CA', 'Irvine', 'CA / Irvine'),
    ('IN', 'Fort Wayne', 'IN / Fort Wayne'),
    ('NJ', 'Jersey City', 'NJ / Jersey City'),
    ('NC', 'Durham', 'NC / Durham'),
    ('FL', 'St. Petersburg', 'FL / St. Petersburg'),
    ('TX', 'Laredo', 'TX / Laredo'),
    ('NY', 'Buffalo', 'NY / Buffalo'),
    ('WI', 'Madison', 'WI / Madison'),
    ('TX', 'Lubbock', 'TX / Lubbock'),
    ('AZ', 'Chandler', 'AZ / Chandler'),
    ('AZ', 'Scottsdale', 'AZ / Scottsdale'),
    ('AZ', 'Glendale', 'AZ / Glendale'),
    ('NV', 'Reno', 'NV / Reno'),
    ('TX', 'Kyle', 'TX / Kyle'),
    ('VA', 'Norfolk', 'VA / Norfolk'),
    ('NC', 'Winston-Salem', 'NC / Winston-Salem'),
    ('NV', 'North Las Vegas', 'NV / North Las Vegas'),
    ('TX', 'Irving', 'TX / Irving'),
    ('VA', 'Chesapeake', 'VA / Chesapeake'),
    ('AZ', 'Gilbert', 'AZ / Gilbert'),
    ('FL', 'Hialeah', 'FL / Hialeah'),
    ('TX', 'Garland', 'TX / Garland'),
    ('CA', 'Fremont', 'CA / Fremont'),
    ('LA', 'Baton Rouge', 'LA / Baton Rouge'),
    ('VA', 'Richmond', 'VA / Richmond'),
    ('ID', 'Boise City', 'ID / Boise City'),
    ('CA', 'San Bernardino', 'CA / San Bernardino'),
    ('WA', 'Spokane', 'WA / Spokane'),
    ('IA', 'Des Moines', 'IA / Des Moines'),
    ('CA', 'Modesto', 'CA / Modesto'),
    ('AL', 'Birmingham', 'AL / Birmingham'),
    ('WA', 'Tacoma', 'WA / Tacoma'),
    ('CA', 'Fontana', 'CA / Fontana'),
    ('NY', 'Rochester', 'NY / Rochester'),
    ('CA', 'Oxnard', 'CA / Oxnard'),
    ('CA', 'Moreno Valley', 'CA / Moreno Valley'),
    ('NC', 'Fayetteville', 'NC / Fayetteville'),
    ('IL', 'Aurora', 'IL / Aurora'),
    ('CA', 'Glendale', 'CA / Glendale'),
    ('NY', 'Yonkers', 'NY / Yonkers'),
    ('CA', 'Huntington Beach', 'CA / Huntington Beach'),
    ('AL', 'Montgomery', 'AL / Montgomery'),
    ('TX', 'Amarillo', 'TX / Amarillo'),
    ('AR', 'Little Rock', 'AR / Little Rock'),
    ('OH', 'Akron', 'OH / Akron'),
    ('GA', 'Columbus', 'GA / Columbus'),
    ('GA', 'Augusta-Richmond County', 'GA / Augusta-Richmond County'),
    ('MI', 'Grand Rapids', 'MI / Grand Rapids'),
    ('LA', 'Shreveport', 'LA / Shreveport'),
    ('UT', 'Salt Lake City', 'UT / Salt Lake City'),
    ('AL', 'Huntsville', 'AL / Huntsville'),
    ('AL', 'Mobile', 'AL / Mobile'),
    ('FL', 'Tallahassee', 'FL / Tallahassee'),
    ('TX', 'Grand Prairie', 'TX / Grand Prairie'),
    ('KS', 'Overland Park', 'KS / Overland Park'),
    ('TN', 'Knoxville', 'TN / Knoxville'),
    ('FL', 'Port St. Lucie', 'FL / Port St. Lucie'),
    ('MA', 'Worcester', 'MA / Worcester'),
    ('TX', 'Brownsville', 'TX / Brownsville'),
    ('AZ', 'Tempe', 'AZ / Tempe'),
    ('CA', 'Santa Clarita', 'CA / Santa Clarita'),
    ('VA', 'Newport News', 'VA / Newport News'),
    ('FL', 'Cape Coral', 'FL / Cape Coral'),
    ('RI', 'Providence', 'RI / Providence'),
    ('FL', 'Fort Lauderdale', 'FL / Fort Lauderdale'),
    ('TN', 'Chattanooga', 'TN / Chattanooga'),
    ('CA', 'Rancho Cucamonga', 'CA / Rancho Cucamonga'),
    ('CA', 'Oceanside', 'CA / Oceanside'),
    ('CA', 'Santa Rosa', 'CA / Santa Rosa'),
    ('CA', 'Garden Grove', 'CA / Garden Grove'),
    ('WA', 'Vancouver', 'WA / Vancouver'),
    ('SD', 'Sioux Falls', 'SD / Sioux Falls'),
    ('CA', 'Ontario', 'CA / Ontario'),
    ('TX', 'McKinney', 'TX / McKinney'),
    ('CA', 'Elk Grove', 'CA / Elk Grove'),
    ('MS', 'Jackson', 'MS / Jackson'),
    ('FL', 'Pembroke Pines', 'FL / Pembroke Pines'),
    ('OR', 'Salem', 'OR / Salem'),
    ('MO', 'Springfield', 'MO / Springfield'),
    ('CA', 'Corona', 'CA / Corona'),
    ('OR', 'Eugene', 'OR / Eugene'),
    ('CO', 'Fort Collins', 'CO / Fort Collins'),
    ('AZ', 'Peoria', 'AZ / Peoria'),
    ('TX', 'Frisco', 'TX / Frisco'),
    ('NC', 'Cary', 'NC / Cary'),
    ('CA', 'Lancaster', 'CA / Lancaster'),
    ('CA', 'Hayward', 'CA / Hayward'),
    ('CA', 'Palmdale', 'CA / Palmdale'),
    ('CA', 'Salinas', 'CA / Salinas'),
    ('VA', 'Alexandria', 'VA / Alexandria'),
    ('CO', 'Lakewood', 'CO / Lakewood'),
    ('MA', 'Springfield', 'MA / Springfield'),
    ('TX', 'Pasadena', 'TX / Pasadena'),
    ('CA', 'Sunnyvale', 'CA / Sunnyvale'),
    ('GA', 'Macon-Bibb County', 'GA / Macon-Bibb County'),
    ('CA', 'Pomona', 'CA / Pomona'),
    ('FL', 'Hollywood', 'FL / Hollywood'),
    ('KS', 'Kansas City', 'KS / Kansas City'),
    ('CA', 'Escondido', 'CA / Escondido'),
    ('TN', 'Clarksville', 'TN / Clarksville'),
    ('IL', 'Joliet', 'IL / Joliet'),
    ('IL', 'Rockford', 'IL / Rockford'),
    ('CA', 'Torrance', 'CA / Torrance'),
    ('IL', 'Naperville', 'IL / Naperville'),
    ('NJ', 'Paterson', 'NJ / Paterson'),
    ('GA', 'Savannah', 'GA / Savannah'),
    ('CT', 'Bridgeport', 'CT / Bridgeport'),
    ('TX', 'Mesquite', 'TX / Mesquite'),
    ('TX', 'Killeen', 'TX / Killeen'),
    ('NY', 'Syracuse', 'NY / Syracuse'),
    ('TX', 'McAllen', 'TX / McAllen'),
    ('CA', 'Pasadena', 'CA / Pasadena'),
    ('WA', 'Bellevue', 'WA / Bellevue'),
    ('CA', 'Fullerton', 'CA / Fullerton'),
    ('CA', 'Orange', 'CA / Orange'),
    ('OH', 'Dayton', 'OH / Dayton'),
    ('FL', 'Miramar', 'FL / Miramar'),
    ('CO', 'Thornton', 'CO / Thornton'),
    ('UT', 'West Valley City', 'UT / West Valley City'),
    ('KS', 'Olathe', 'KS / Olathe'),
    ('VA', 'Hampton', 'VA / Hampton'),
    ('MI', 'Warren', 'MI / Warren'),
    ('TX', 'Midland', 'TX / Midland'),
    ('TX', 'Waco', 'TX / Waco'),
    ('SC', 'Charleston', 'SC / Charleston'),
    ('SC', 'Columbia', 'SC / Columbia'),
    ('TX', 'Denton', 'TX / Denton'),
    ('TX', 'Carrollton', 'TX / Carrollton'),
    ('AZ', 'Surprise', 'AZ / Surprise'),
    ('CA', 'Roseville', 'CA / Roseville'),
    ('MI', 'Sterling Heights', 'MI / Sterling Heights'),
    ('TN', 'Murfreesboro', 'TN / Murfreesboro'),
    ('FL', 'Gainesville', 'FL / Gainesville'),
    ('IA', 'Cedar Rapids', 'IA / Cedar Rapids'),
    ('CA', 'Visalia', 'CA / Visalia'),
    ('FL', 'Coral Springs', 'FL / Coral Springs'),
    ('CT', 'New Haven', 'CT / New Haven'),
    ('CT', 'Stamford', 'CT / Stamford'),
    ('CA', 'Thousand Oaks', 'CA / Thousand Oaks'),
    ('CA', 'Concord', 'CA / Concord'),
    ('NJ', 'Elizabeth', 'NJ / Elizabeth'),
    ('LA', 'Lafayette', 'LA / Lafayette'),
    ('WA', 'Kent', 'WA / Kent'),
    ('KS', 'Topeka', 'KS / Topeka'),
    ('CA', 'Simi Valley', 'CA / Simi Valley'),
    ('CA', 'Santa Clara', 'CA / Santa Clara'),
    ('GA', 'Athens-Clarke County', 'GA / Athens-Clarke County'),
    ('CT', 'Hartford', 'CT / Hartford'),
    ('CA', 'Victorville', 'CA / Victorville'),
    ('TX', 'Abilene', 'TX / Abilene'),
    ('OK', 'Norman', 'OK / Norman'),
    ('CA', 'Vallejo', 'CA / Vallejo'),
    ('CA', 'Berkeley', 'CA / Berkeley'),
    ('TX', 'Round Rock', 'TX / Round Rock'),
    ('MI', 'Ann Arbor', 'MI / Ann Arbor'),
    ('ND', 'Fargo', 'ND / Fargo'),
    ('MO', 'Columbia', 'MO / Columbia'),
    ('PA', 'Allentown', 'PA / Allentown'),
    ('IN', 'Evansville', 'IN / Evansville'),
    ('TX', 'Beaumont', 'TX / Beaumont'),
    ('TX', 'Odessa', 'TX / Odessa'),
    ('NC', 'Wilmington', 'NC / Wilmington'),
    ('CO', 'Arvada', 'CO / Arvada'),
    ('MO', 'Independence', 'MO / Independence'),
    ('UT', 'Provo', 'UT / Provo'),
    ('MI', 'Lansing', 'MI / Lansing'),
    ('CA', 'El Monte', 'CA / El Monte'),
    ('IL', 'Springfield', 'IL / Springfield'),
    ('CA', 'Fairfield', 'CA / Fairfield'),
    ('FL', 'Clearwater', 'FL / Clearwater'),
    ('IL', 'Peoria', 'IL / Peoria'),
    ('MN', 'Rochester', 'MN / Rochester'),
    ('CA', 'Carlsbad', 'CA / Carlsbad'),
    ('CO', 'Westminster', 'CO / Westminster'),
    ('UT', 'West Jordan', 'UT / West Jordan'),
    ('TX', 'Pearland', 'TX / Pearland'),
    ('TX', 'Richardson', 'TX / Richardson'),
    ('CA', 'Downey', 'CA / Downey'),
    ('FL', 'Miami Gardens', 'FL / Miami Gardens'),
    ('CA', 'Temecula', 'CA / Temecula'),
    ('CA', 'Costa Mesa', 'CA / Costa Mesa'),
    ('TX', 'College Station', 'TX / College Station'),
    ('IL', 'Elgin', 'IL / Elgin'),
    ('CA', 'Murrieta', 'CA / Murrieta'),
    ('OR', 'Gresham', 'OR / Gresham'),
    ('NC', 'High Point', 'NC / High Point'),
    ('CA', 'Antioch', 'CA / Antioch'),
    ('CA', 'Inglewood', 'CA / Inglewood'),
    ('MA', 'Cambridge', 'MA / Cambridge'),
    ('MA', 'Lowell', 'MA / Lowell'),
    ('NH', 'Manchester', 'NH / Manchester'),
    ('MT', 'Billings', 'MT / Billings'),
    ('CO', 'Pueblo', 'CO / Pueblo'),
    ('FL', 'Palm Bay', 'FL / Palm Bay'),
    ('CO', 'Centennial', 'CO / Centennial'),
    ('CA', 'Richmond', 'CA / Richmond'),
    ('CA', 'San Buenaventura (Ventura)', 'CA / San Buenaventura (Ventura)'),
    ('FL', 'Pompano Beach', 'FL / Pompano Beach'),
    ('SC', 'North Charleston', 'SC / North Charleston'),
    ('WA', 'Everett', 'WA / Everett'),
    ('CT', 'Waterbury', 'CT / Waterbury'),
    ('FL', 'West Palm Beach', 'FL / West Palm Beach'),
    ('CO', 'Boulder', 'CO / Boulder'),
    ('CA', 'West Covina', 'CA / West Covina'),
    ('OK', 'Broken Arrow', 'OK / Broken Arrow'),
    ('CA', 'Clovis', 'CA / Clovis'),
    ('CA', 'Daly City', 'CA / Daly City'),
    ('FL', 'Lakeland', 'FL / Lakeland'),
    ('CA', 'Santa Maria', 'CA / Santa Maria'),
    ('CA', 'Norwalk', 'CA / Norwalk'),
    ('GA', 'Sandy Springs', 'GA / Sandy Springs'),
    ('OR', 'Hillsboro', 'OR / Hillsboro'),
    ('WI', 'Green Bay', 'WI / Green Bay'),
    ('TX', 'Tyler', 'TX / Tyler'),
    ('TX', 'Wichita Falls', 'TX / Wichita Falls'),
    ('TX', 'Lewisville', 'TX / Lewisville'),
    ('CA', 'Burbank', 'CA / Burbank'),
    ('CO', 'Greeley', 'CO / Greeley'),
    ('CA', 'San Mateo', 'CA / San Mateo'),
    ('CA', 'El Cajon', 'CA / El Cajon'),
    ('CA', 'Jurupa Valley', 'CA / Jurupa Valley'),
    ('CA', 'Rialto', 'CA / Rialto'),
    ('IA', 'Davenport', 'IA / Davenport'),
    ('TX', 'League City', 'TX / League City'),
    ('FL', 'Davie', 'FL / Davie'),
    ('NM', 'Las Cruces', 'NM / Las Cruces'),
    ('IN', 'South Bend', 'IN / South Bend'),
    ('CA', 'Vista', 'CA / Vista'),
    ('WA', 'Renton', 'WA / Renton'),
    ('TX', 'San Angelo', 'TX / San Angelo'),
    ('VA', 'Roanoke', 'VA / Roanoke'),
    ('WI', 'Kenosha', 'WI / Kenosha'),
    ('AL', 'Tuscaloosa', 'AL / Tuscaloosa'),
    ('TX', 'Allen', 'TX / Allen'),
    ('PA', 'Erie', 'PA / Erie'),
    ('NV', 'Sparks', 'NV / Sparks'),
    ('CA', 'Vacaville', 'CA / Vacaville'),
    ('NY', 'Albany', 'NY / Albany'),
    ('OR', 'Beaverton', 'OR / Beaverton'),
    ('CA', 'Compton', 'CA / Compton'),
    ('UT', 'Orem', 'UT / Orem'),
    ('MI', 'Flint', 'MI / Flint'),
    ('WA', 'Federal Way', 'WA / Federal Way'),
    ('CA', 'Mission Viejo', 'CA / Mission Viejo'),
    ('WA', 'Spokane Valley', 'WA / Spokane Valley'),
    ('FL', 'Boca Raton', 'FL / Boca Raton'),
    ('MO', 'Lee''s Summit', 'MO / Lee''s Summit'),
    ('NM', 'Rio Rancho', 'NM / Rio Rancho'),
    ('UT', 'Sandy', 'UT / Sandy'),
    ('MA', 'Brockton', 'MA / Brockton'),
    ('ID', 'Meridian', 'ID / Meridian'),
    ('CA', 'South Gate', 'CA / South Gate'),
    ('KS', 'Lawrence', 'KS / Lawrence'),
    ('CA', 'San Marcos', 'CA / San Marcos'),
    ('VA', 'Portsmouth', 'VA / Portsmouth'),
    ('MA', 'New Bedford', 'MA / New Bedford'),
    ('AZ', 'Yuma', 'AZ / Yuma'),
    ('OK', 'Lawton', 'OK / Lawton'),
    ('GA', 'Roswell', 'GA / Roswell'),
    ('MI', 'Dearborn', 'MI / Dearborn'),
    ('MI', 'Livonia', 'MI / Livonia'),
    ('WA', 'Yakima', 'WA / Yakima'),
    ('FL', 'Sunrise', 'FL / Sunrise'),
    ('CA', 'Hesperia', 'CA / Hesperia'),
    ('MA', 'Quincy', 'MA / Quincy'),
    ('CO', 'Longmont', 'CO / Longmont'),
    ('CA', 'Carson', 'CA / Carson'),
    ('FL', 'Plantation', 'FL / Plantation'),
    ('MA', 'Lynn', 'MA / Lynn'),
    ('CA', 'Santa Monica', 'CA / Santa Monica'),
    ('CA', 'Santa Barbara', 'CA / Santa Barbara'),
    ('FL', 'Miami Beach', 'FL / Miami Beach'),
    ('CA', 'Redding', 'CA / Redding'),
    ('CA', 'Chico', 'CA / Chico'),
    ('CA', 'Westminster', 'CA / Westminster'),
    ('NC', 'Greenville', 'NC / Greenville'),
    ('ID', 'Nampa', 'ID / Nampa'),
    ('OK', 'Edmond', 'OK / Edmond'),
    ('OR', 'Bend', 'OR / Bend'),
    ('IN', 'Carmel', 'IN / Carmel'),
    ('CA', 'San Leandro', 'CA / San Leandro'),
    ('IN', 'Fishers', 'IN / Fishers'),
    ('FL', 'Deltona', 'FL / Deltona'),
    ('NC', 'Concord', 'NC / Concord'),
    ('CA', 'Tracy', 'CA / Tracy'),
    ('VA', 'Suffolk', 'VA / Suffolk'),
    ('NC', 'Asheville', 'NC / Asheville'),
    ('CA', 'Livermore', 'CA / Livermore'),
    ('MA', 'Newton', 'MA / Newton'),
    ('MA', 'Fall River', 'MA / Fall River'),
    ('CA', 'Menifee', 'CA / Menifee'),
    ('CA', 'Indio', 'CA / Indio'),
    ('CT', 'Norwalk', 'CT / Norwalk'),
    ('IL', 'Waukegan', 'IL / Waukegan'),
    ('TX', 'Sugar Land', 'TX / Sugar Land'),
    ('AR', 'Fort Smith', 'AR / Fort Smith'),
    ('CA', 'Hawthorne', 'CA / Hawthorne'),
    ('NH', 'Nashua', 'NH / Nashua'),
    ('CA', 'Chino', 'CA / Chino'),
    ('WA', 'Kirkland', 'WA / Kirkland'),
    ('TX', 'Edinburg', 'TX / Edinburg'),
    ('PA', 'Reading', 'PA / Reading'),
    ('WA', 'Bellingham', 'WA / Bellingham'),
    ('CA', 'Citrus Heights', 'CA / Citrus Heights'),
    ('CA', 'Whittier', 'CA / Whittier'),
    ('UT', 'Ogden', 'UT / Ogden'),
    ('CA', 'Newport Beach', 'CA / Newport Beach'),
    ('IL', 'Champaign', 'IL / Champaign'),
    ('MN', 'Duluth', 'MN / Duluth'),
    ('MO', 'O''Fallon', 'MO / O''Fallon'),
    ('NJ', 'Clifton', 'NJ / Clifton'),
    ('CA', 'Alhambra', 'CA / Alhambra'),
    ('MN', 'Bloomington', 'MN / Bloomington'),
    ('FL', 'Palm Coast', 'FL / Palm Coast'),
    ('CT', 'Danbury', 'CT / Danbury'),
    ('AL', 'Hoover', 'AL / Hoover'),
    ('CA', 'Redwood City', 'CA / Redwood City'),
    ('IN', 'Bloomington', 'IN / Bloomington'),
    ('CA', 'Hemet', 'CA / Hemet'),
    ('SC', 'Mount Pleasant', 'SC / Mount Pleasant'),
    ('NJ', 'Trenton', 'NJ / Trenton'),
    ('NM', 'Santa Fe', 'NM / Santa Fe'),
    ('GA', 'Johns Creek', 'GA / Johns Creek'),
    ('AR', 'Fayetteville', 'AR / Fayetteville'),
    ('MI', 'Troy', 'MI / Troy'),
    ('TX', 'Mission', 'TX / Mission'),
    ('TX', 'Bryan', 'TX / Bryan'),
    ('CA', 'Lake Forest', 'CA / Lake Forest'),
    ('CA', 'Buena Park', 'CA / Buena Park'),
    ('FL', 'Largo', 'FL / Largo'),
    ('IL', 'Cicero', 'IL / Cicero'),
    ('AZ', 'Avondale', 'AZ / Avondale'),
    ('IA', 'Sioux City', 'IA / Sioux City'),
    ('CA', 'Merced', 'CA / Merced'),
    ('UT', 'St. George', 'UT / St. George'),
    ('TX', 'Conroe', 'TX / Conroe'),
    ('CA', 'Pleasanton', 'CA / Pleasanton'),
    ('TX', 'Longview', 'TX / Longview'),
    ('OR', 'Medford', 'OR / Medford'),
    ('RI', 'Warwick', 'RI / Warwick'),
    ('MI', 'Westland', 'MI / Westland'),
    ('MA', 'Somerville', 'MA / Somerville'),
    ('FL', 'Melbourne', 'FL / Melbourne'),
    ('CA', 'Lakewood', 'CA / Lakewood'),
    ('MI', 'Farmington Hills', 'MI / Farmington Hills'),
    ('RI', 'Cranston', 'RI / Cranston'),
    ('WA', 'Kennewick', 'WA / Kennewick'),
    ('CA', 'Mountain View', 'CA / Mountain View'),
    ('CA', 'Napa', 'CA / Napa'),
    ('CA', 'Tustin', 'CA / Tustin'),
    ('VA', 'Lynchburg', 'VA / Lynchburg'),
    ('MA', 'Lawrence', 'MA / Lawrence'),
    ('FL', 'Deerfield Beach', 'FL / Deerfield Beach'),
    ('MN', 'Brooklyn Park', 'MN / Brooklyn Park'),
    ('NY', 'New Rochelle', 'NY / New Rochelle'),
    ('OH', 'Parma', 'OH / Parma'),
    ('CA', 'Alameda', 'CA / Alameda'),
    ('CA', 'Chino Hills', 'CA / Chino Hills'),
    ('AR', 'Springdale', 'AR / Springdale'),
    ('IL', 'Bloomington', 'IL / Bloomington'),
    ('CA', 'Bellflower', 'CA / Bellflower'),
    ('WI', 'Racine', 'WI / Racine'),
    ('CA', 'Milpitas', 'CA / Milpitas'),
    ('WA', 'Auburn', 'WA / Auburn'),
    ('TX', 'Pharr', 'TX / Pharr'),
    ('PA', 'Scranton', 'PA / Scranton'),
    ('CA', 'Folsom', 'CA / Folsom'),
    ('AZ', 'Goodyear', 'AZ / Goodyear'),
    ('MN', 'Plymouth', 'MN / Plymouth'),
    ('FL', 'Fort Myers', 'FL / Fort Myers'),
    ('IN', 'Hammond', 'IN / Hammond'),
    ('CA', 'Manteca', 'CA / Manteca'),
    ('CO', 'Loveland', 'CO / Loveland'),
    ('LA', 'Lake Charles', 'LA / Lake Charles'),
    ('CA', 'Upland', 'CA / Upland'),
    ('MO', 'St. Joseph', 'MO / St. Joseph'),
    ('CA', 'Baldwin Park', 'CA / Baldwin Park'),
    ('IN', 'Gary', 'IN / Gary'),
    ('CA', 'Perris', 'CA / Perris'),
    ('TX', 'Baytown', 'TX / Baytown'),
    ('MI', 'Kalamazoo', 'MI / Kalamazoo'),
    ('UT', 'Layton', 'UT / Layton'),
    ('CA', 'San Ramon', 'CA / San Ramon'),
    ('FL', 'Boynton Beach', 'FL / Boynton Beach'),
    ('MI', 'Wyoming', 'MI / Wyoming'),
    ('NC', 'Gastonia', 'NC / Gastonia'),
    ('IL', 'Arlington Heights', 'IL / Arlington Heights'),
    ('CA', 'Union City', 'CA / Union City'),
    ('PA', 'Bethlehem', 'PA / Bethlehem'),
    ('IL', 'Evanston', 'IL / Evanston'),
    ('AR', 'Jonesboro', 'AR / Jonesboro'),
    ('TN', 'Franklin', 'TN / Franklin'),
    ('TX', 'Missouri City', 'TX / Missouri City'),
    ('IL', 'Bolingbrook', 'IL / Bolingbrook'),
    ('IL', 'Schaumburg', 'IL / Schaumburg'),
    ('NJ', 'Camden', 'NJ / Camden'),
    ('IA', 'Iowa City', 'IA / Iowa City'),
    ('GA', 'Warner Robins', 'GA / Warner Robins'),
    ('WI', 'Appleton', 'WI / Appleton'),
    ('SD', 'Rapid City', 'SD / Rapid City'),
    ('TX', 'New Braunfels', 'TX / New Braunfels'),
    ('GA', 'Albany', 'GA / Albany'),
    ('TX', 'Temple', 'TX / Temple'),
    ('TX', 'Flower Mound', 'TX / Flower Mound'),
    ('MI', 'Rochester Hills', 'MI / Rochester Hills'),
    ('MI', 'Southfield', 'MI / Southfield'),
    ('SC', 'Rock Hill', 'SC / Rock Hill'),
    ('CA', 'Turlock', 'CA / Turlock'),
    ('IL', 'Decatur', 'IL / Decatur'),
    ('CT', 'New Britain', 'CT / New Britain'),
    ('CA', 'Apple Valley', 'CA / Apple Valley'),
    ('ND', 'Bismarck', 'ND / Bismarck'),
    ('MT', 'Missoula', 'MT / Missoula'),
    ('WI', 'Waukesha', 'WI / Waukesha'),
    ('CA', 'Rancho Cordova', 'CA / Rancho Cordova'),
    ('MS', 'Gulfport', 'MS / Gulfport'),
    ('IN', 'Lafayette', 'IN / Lafayette'),
    ('FL', 'Lauderhill', 'FL / Lauderhill'),
    ('AZ', 'Flagstaff', 'AZ / Flagstaff'),
    ('DE', 'Wilmington', 'DE / Wilmington'),
    ('RI', 'Pawtucket', 'RI / Pawtucket'),
    ('OH', 'Canton', 'OH / Canton'),
    ('CA', 'Redlands', 'CA / Redlands'),
    ('CA', 'Lynwood', 'CA / Lynwood'),
    ('CA', 'Pittsburg', 'CA / Pittsburg'),
    ('NJ', 'Passaic', 'NJ / Passaic'),
    ('WA', 'Pasco', 'WA / Pasco'),
    ('MD', 'Frederick', 'MD / Frederick'),
    ('FL', 'Weston', 'FL / Weston'),
    ('TX', 'North Richland Hills', 'TX / North Richland Hills'),
    ('MN', 'Maple Grove', 'MN / Maple Grove'),
    ('FL', 'Kissimmee', 'FL / Kissimmee'),
    ('NJ', 'Union City', 'NJ / Union City'),
    ('MO', 'St. Charles', 'MO / St. Charles'),
    ('CA', 'Walnut Creek', 'CA / Walnut Creek'),
    ('UT', 'South Jordan', 'UT / South Jordan'),
    ('IN', 'Muncie', 'IN / Muncie'),
    ('TX', 'Cedar Park', 'TX / Cedar Park'),
    ('MN', 'Woodbury', 'MN / Woodbury'),
    ('IL', 'Palatine', 'IL / Palatine'),
    ('LA', 'Bossier City', 'LA / Bossier City'),
    ('AL', 'Dothan', 'AL / Dothan'),
    ('NY', 'Mount Vernon', 'NY / Mount Vernon'),
    ('WI', 'Eau Claire', 'WI / Eau Claire'),
    ('CA', 'Yorba Linda', 'CA / Yorba Linda'),
    ('CA', 'Davis', 'CA / Davis'),
    ('FL', 'Homestead', 'FL / Homestead'),
    ('IA', 'Waterloo', 'IA / Waterloo'),
    ('CA', 'Redondo Beach', 'CA / Redondo Beach'),
    ('NC', 'Jacksonville', 'NC / Jacksonville'),
    ('MD', 'Gaithersburg', 'MD / Gaithersburg'),
    ('TX', 'Victoria', 'TX / Victoria'),
    ('MN', 'St. Cloud', 'MN / St. Cloud'),
    ('WA', 'Marysville', 'WA / Marysville'),
    ('SC', 'Greenville', 'SC / Greenville'),
    ('FL', 'Delray Beach', 'FL / Delray Beach'),
    ('CA', 'Camarillo', 'CA / Camarillo'),
    ('TX', 'Georgetown', 'TX / Georgetown'),
    ('LA', 'Kenner', 'LA / Kenner'),
    ('CA', 'Palo Alto', 'CA / Palo Alto'),
    ('TN', 'Jackson', 'TN / Jackson'),
    ('CA', 'South San Francisco', 'CA / South San Francisco'),
    ('MD', 'Rockville', 'MD / Rockville'),
    ('ME', 'Portland', 'ME / Portland'),
    ('CA', 'Yuba City', 'CA / Yuba City'),
    ('TN', 'Johnson City', 'TN / Johnson City'),
    ('FL', 'Daytona Beach', 'FL / Daytona Beach'),
    ('WI', 'Oshkosh', 'WI / Oshkosh'),
    ('CO', 'Broomfield', 'CO / Broomfield'),
    ('MN', 'Eagan', 'MN / Eagan'),
    ('AR', 'North Little Rock', 'AR / North Little Rock'),
    ('NJ', 'Bayonne', 'NJ / Bayonne'),
    ('IA', 'Ames', 'IA / Ames'),
    ('TX', 'Mansfield', 'TX / Mansfield'),
    ('TX', 'Harlingen', 'TX / Harlingen'),
    ('GA', 'Alpharetta', 'GA / Alpharetta'),
    ('CA', 'Laguna Niguel', 'CA / Laguna Niguel'),
    ('CA', 'San Clemente', 'CA / San Clemente'),
    ('AR', 'Conway', 'AR / Conway'),
    ('KY', 'Bowling Green', 'KY / Bowling Green'),
    ('FL', 'Tamarac', 'FL / Tamarac'),
    ('KS', 'Shawnee', 'KS / Shawnee'),
    ('AR', 'Rogers', 'AR / Rogers'),
    ('NY', 'Schenectady', 'NY / Schenectady'),
    ('NJ', 'East Orange', 'NJ / East Orange'),
    ('CA', 'Lodi', 'CA / Lodi'),
    ('AZ', 'Buckeye', 'AZ / Buckeye'),
    ('IA', 'West Des Moines', 'IA / West Des Moines'),
    ('CA', 'Santa Cruz', 'CA / Santa Cruz'),
    ('CA', 'Madera', 'CA / Madera'),
    ('OH', 'Youngstown', 'OH / Youngstown'),
    ('FL', 'North Port', 'FL / North Port'),
    ('IL', 'Skokie', 'IL / Skokie'),
    ('CA', 'Lake Elsinore', 'CA / Lake Elsinore'),
    ('WI', 'Janesville', 'WI / Janesville'),
    ('WY', 'Cheyenne', 'WY / Cheyenne'),
    ('MN', 'Eden Prairie', 'MN / Eden Prairie'),
    ('FL', 'Wellington', 'FL / Wellington'),
    ('FL', 'Jupiter', 'FL / Jupiter'),
    ('WA', 'Sammamish', 'WA / Sammamish'),
    ('OH', 'Lorain', 'OH / Lorain'),
    ('CA', 'Pico Rivera', 'CA / Pico Rivera'),
    ('CA', 'Montebello', 'CA / Montebello'),
    ('CA', 'Encinitas', 'CA / Encinitas'),
    ('AL', 'Auburn', 'AL / Auburn'),
    ('MA', 'Waltham', 'MA / Waltham'),
    ('MN', 'Blaine', 'MN / Blaine'),
    ('MA', 'Haverhill', 'MA / Haverhill'),
    ('CA', 'Rocklin', 'CA / Rocklin'),
    ('CA', 'Tulare', 'CA / Tulare'),
    ('IA', 'Council Bluffs', 'IA / Council Bluffs'),
    ('WA', 'Redmond', 'WA / Redmond'),
    ('MN', 'Coon Rapids', 'MN / Coon Rapids'),
    ('FL', 'North Miami', 'FL / North Miami'),
    ('OH', 'Hamilton', 'OH / Hamilton'),
    ('TX', 'Rowlett', 'TX / Rowlett'),
    ('TX', 'San Marcos', 'TX / San Marcos'),
    ('MN', 'Lakeville', 'MN / Lakeville'),
    ('OR', 'Springfield', 'OR / Springfield'),
    ('CO', 'Grand Junction', 'CO / Grand Junction'),
    ('CA', 'La Habra', 'CA / La Habra'),
    ('OK', 'Moore', 'OK / Moore'),
    ('MN', 'Burnsville', 'MN / Burnsville'),
    ('MI', 'Taylor', 'MI / Taylor'),
    ('CA', 'Eastvale', 'CA / Eastvale'),
    ('CA', 'National City', 'CA / National City'),
    ('UT', 'Lehi', 'UT / Lehi'),
    ('FL', 'Port Orange', 'FL / Port Orange'),
    ('CA', 'Monterey Park', 'CA / Monterey Park'),
    ('GA', 'Marietta', 'GA / Marietta'),
    ('IN', 'Terre Haute', 'IN / Terre Haute'),
    ('MA', 'Malden', 'MA / Malden'),
    ('WA', 'Lakewood', 'WA / Lakewood'),
    ('NY', 'Utica', 'NY / Utica'),
    ('CA', 'Cupertino', 'CA / Cupertino'),
    ('CA', 'Brentwood', 'CA / Brentwood'),
    ('CA', 'Petaluma', 'CA / Petaluma'),
    ('NJ', 'Vineland', 'NJ / Vineland'),
    ('UT', 'Taylorsville', 'UT / Taylorsville'),
    ('ID', 'Idaho Falls', 'ID / Idaho Falls'),
    ('IN', 'Noblesville', 'IN / Noblesville'),
    ('CT', 'Bristol', 'CT / Bristol'),
    ('WI', 'West Allis', 'WI / West Allis'),
    ('CA', 'Gardena', 'CA / Gardena'),
    ('CA', 'La Mesa', 'CA / La Mesa'),
    ('MI', 'St. Clair Shores', 'MI / St. Clair Shores'),
    ('MI', 'Pontiac', 'MI / Pontiac'),
    ('CT', 'Meriden', 'CT / Meriden'),
    ('CA', 'Dublin', 'CA / Dublin'),
    ('FL', 'Coconut Creek', 'FL / Coconut Creek'),
    ('WY', 'Casper', 'WY / Casper'),
    ('KY', 'Owensboro', 'KY / Owensboro'),
    ('FL', 'Ocala', 'FL / Ocala'),
    ('NC', 'Chapel Hill', 'NC / Chapel Hill'),
    ('TX', 'Pflugerville', 'TX / Pflugerville'),
    ('PA', 'Lancaster', 'PA / Lancaster'),
    ('MI', 'Novi', 'MI / Novi'),
    ('MT', 'Great Falls', 'MT / Great Falls'),
    ('OH', 'Springfield', 'OH / Springfield'),
    ('CA', 'Woodland', 'CA / Woodland'),
    ('MI', 'Royal Oak', 'MI / Royal Oak'),
    ('CA', 'Porterville', 'CA / Porterville'),
    ('CA', 'San Rafael', 'CA / San Rafael'),
    ('CA', 'Huntington Park', 'CA / Huntington Park'),
    ('IL', 'Orland Park', 'IL / Orland Park'),
    ('TN', 'Bartlett', 'TN / Bartlett'),
    ('FL', 'Sanford', 'FL / Sanford'),
    ('IA', 'Dubuque', 'IA / Dubuque'),
    ('CA', 'Arcadia', 'CA / Arcadia'),
    ('MD', 'Bowie', 'MD / Bowie'),
    ('NY', 'White Plains', 'NY / White Plains'),
    ('IL', 'Des Plaines', 'IL / Des Plaines'),
    ('FL', 'Doral', 'FL / Doral'),
    ('FL', 'Margate', 'FL / Margate'),
    ('CA', 'Santee', 'CA / Santee'),
    ('IN', 'Kokomo', 'IN / Kokomo'),
    ('CO', 'Castle Rock', 'CO / Castle Rock'),
    ('ND', 'Grand Forks', 'ND / Grand Forks'),
    ('OK', 'Midwest City', 'OK / Midwest City'),
    ('MO', 'St. Peters', 'MO / St. Peters'),
    ('MA', 'Medford', 'MA / Medford'),
    ('OR', 'Corvallis', 'OR / Corvallis'),
    ('TN', 'Hendersonville', 'TN / Hendersonville'),
    ('NJ', 'New Brunswick', 'NJ / New Brunswick'),
    ('MA', 'Taunton', 'MA / Taunton'),
    ('IL', 'Tinley Park', 'IL / Tinley Park'),
    ('CA', 'Diamond Bar', 'CA / Diamond Bar'),
    ('GA', 'Smyrna', 'GA / Smyrna'),
    ('FL', 'Sarasota', 'FL / Sarasota'),
    ('IN', 'Greenwood', 'IN / Greenwood'),
    ('CA', 'Fountain Valley', 'CA / Fountain Valley'),
    ('GA', 'Valdosta', 'GA / Valdosta'),
    ('IL', 'Oak Lawn', 'IL / Oak Lawn'),
    ('CA', 'Novato', 'CA / Novato'),
    ('MA', 'Chicopee', 'MA / Chicopee'),
    ('MA', 'Weymouth Town', 'MA / Weymouth Town'),
    ('MI', 'Dearborn Heights', 'MI / Dearborn Heights'),
    ('IL', 'Berwyn', 'IL / Berwyn'),
    ('FL', 'Bradenton', 'FL / Bradenton'),
    ('NY', 'Hempstead', 'NY / Hempstead'),
    ('CA', 'Hanford', 'CA / Hanford'),
    ('NC', 'Rocky Mount', 'NC / Rocky Mount'),
    ('TX', 'Port Arthur', 'TX / Port Arthur'),
    ('WA', 'Shoreline', 'WA / Shoreline'),
    ('OH', 'Kettering', 'OH / Kettering'),
    ('IN', 'Anderson', 'IN / Anderson'),
    ('AL', 'Decatur', 'AL / Decatur'),
    ('CA', 'Gilroy', 'CA / Gilroy'),
    ('WA', 'Richland', 'WA / Richland'),
    ('KS', 'Manhattan', 'KS / Manhattan'),
    ('CA', 'Highland', 'CA / Highland'),
    ('CA', 'Paramount', 'CA / Paramount'),
    ('CO', 'Commerce City', 'CO / Commerce City'),
    ('NC', 'Huntersville', 'NC / Huntersville'),
    ('TX', 'Euless', 'TX / Euless'),
    ('ID', 'Pocatello', 'ID / Pocatello'),
    ('NV', 'Carson City', 'NV / Carson City'),
    ('CA', 'Colton', 'CA / Colton'),
    ('AZ', 'Casa Grande', 'AZ / Casa Grande'),
    ('CT', 'West Haven', 'CT / West Haven'),
    ('CA', 'Rosemead', 'CA / Rosemead'),
    ('MO', 'Blue Springs', 'MO / Blue Springs'),
    ('NJ', 'Hoboken', 'NJ / Hoboken'),
    ('IL', 'Normal', 'IL / Normal'),
    ('FL', 'Bonita Springs', 'FL / Bonita Springs'),
    ('IL', 'Mount Prospect', 'IL / Mount Prospect'),
    ('CA', 'Cathedral City', 'CA / Cathedral City'),
    ('CA', 'Watsonville', 'CA / Watsonville'),
    ('FL', 'Pensacola', 'FL / Pensacola'),
    ('FL', 'Palm Beach Gardens', 'FL / Palm Beach Gardens'),
    ('AZ', 'Lake Havasu City', 'AZ / Lake Havasu City'),
    ('OH', 'Elyria', 'OH / Elyria'),
    ('NE', 'Bellevue', 'NE / Bellevue'),
    ('IL', 'Wheaton', 'IL / Wheaton'),
    ('NJ', 'West New York', 'NJ / West New York'),
    ('CA', 'Yucaipa', 'CA / Yucaipa'),
    ('MS', 'Southaven', 'MS / Southaven'),
    ('OR', 'Albany', 'OR / Albany'),
    ('MA', 'Revere', 'MA / Revere'),
    ('ID', 'Caldwell', 'ID / Caldwell'),
    ('VA', 'Harrisonburg', 'VA / Harrisonburg'),
    ('CA', 'West Sacramento', 'CA / West Sacramento'),
    ('KS', 'Lenexa', 'KS / Lenexa'),
    ('TN', 'Kingsport', 'TN / Kingsport'),
    ('NC', 'Burlington', 'NC / Burlington'),
    ('CA', 'Delano', 'CA / Delano'),
    ('VA', 'Leesburg', 'VA / Leesburg'),
    ('TX', 'DeSoto', 'TX / DeSoto'),
    ('CT', 'Milford', 'CT / Milford'),
    ('NJ', 'Perth Amboy', 'NJ / Perth Amboy'),
    ('MA', 'Peabody', 'MA / Peabody'),
    ('GA', 'Brookhaven', 'GA / Brookhaven'),
    ('MN', 'Minnetonka', 'MN / Minnetonka'),
    ('CA', 'Palm Desert', 'CA / Palm Desert'),
    ('CA', 'Placentia', 'CA / Placentia'),
    ('IN', 'Elkhart', 'IN / Elkhart'),
    ('MO', 'Joplin', 'MO / Joplin'),
    ('FL', 'Pinellas Park', 'FL / Pinellas Park'),
    ('WI', 'La Crosse', 'WI / La Crosse'),
    ('TX', 'Grapevine', 'TX / Grapevine'),
    ('MN', 'Apple Valley', 'MN / Apple Valley'),
    ('OR', 'Tigard', 'OR / Tigard'),
    ('CA', 'Glendora', 'CA / Glendora'),
    ('MO', 'Florissant', 'MO / Florissant'),
    ('IL', 'Oak Park', 'IL / Oak Park'),
    ('IL', 'Hoffman Estates', 'IL / Hoffman Estates'),
    ('MI', 'Kentwood', 'MI / Kentwood'),
    ('MI', 'Battle Creek', 'MI / Battle Creek'),
    ('NE', 'Grand Island', 'NE / Grand Island'),
    ('CA', 'Aliso Viejo', 'CA / Aliso Viejo'),
    ('MN', 'Edina', 'MN / Edina'),
    ('WA', 'Olympia', 'WA / Olympia'),
    ('CO', 'Parker', 'CO / Parker'),
    ('OK', 'Enid', 'OK / Enid'),
    ('WA', 'Burien', 'WA / Burien'),
    ('FL', 'Coral Gables', 'FL / Coral Gables'),
    ('UT', 'Logan', 'UT / Logan'),
    ('NJ', 'Plainfield', 'NJ / Plainfield'),
    ('CA', 'Cerritos', 'CA / Cerritos'),
    ('TX', 'Galveston', 'TX / Galveston'),
    ('ID', 'Coeur d''Alene', 'ID / Coeur d''Alene'),
    ('OH', 'Lakewood', 'OH / Lakewood'),
    ('CA', 'Poway', 'CA / Poway'),
    ('MA', 'Methuen', 'MA / Methuen'),
    ('NY', 'Troy', 'NY / Troy'),
    ('CA', 'Azusa', 'CA / Azusa'),
    ('NC', 'Wilson', 'NC / Wilson'),
    ('TX', 'Bedford', 'TX / Bedford'),
    ('OK', 'Stillwater', 'OK / Stillwater'),
    ('IL', 'Downers Grove', 'IL / Downers Grove'),
    ('FL', 'Apopka', 'FL / Apopka'),
    ('SC', 'Summerville', 'SC / Summerville'),
    ('LA', 'Monroe', 'LA / Monroe'),
    ('UT', 'Murray', 'UT / Murray'),
    ('CA', 'La Mirada', 'CA / La Mirada'),
    ('OH', 'Cuyahoga Falls', 'OH / Cuyahoga Falls'),
    ('TN', 'Collierville', 'TN / Collierville'),
    ('WV', 'Charleston', 'WV / Charleston'),
    ('OH', 'Newark', 'OH / Newark'),
    ('MI', 'Saginaw', 'MI / Saginaw'),
    ('CA', 'Rancho Santa Margarita', 'CA / Rancho Santa Margarita'),
    ('CA', 'Cypress', 'CA / Cypress'),
    ('PA', 'Harrisburg', 'PA / Harrisburg'),
    ('GA', 'Dunwoody', 'GA / Dunwoody'),
    ('MI', 'East Lansing', 'MI / East Lansing'),
    ('OH', 'Middletown', 'OH / Middletown'),
    ('MN', 'St. Louis Park', 'MN / St. Louis Park'),
    ('ND', 'Minot', 'ND / Minot'),
    ('WI', 'Sheboygan', 'WI / Sheboygan'),
    ('IN', 'Mishawaka', 'IN / Mishawaka'),
    ('NY', 'Niagara Falls', 'NY / Niagara Falls'),
    ('TN', 'Smyrna', 'TN / Smyrna'),
    ('CA', 'Covina', 'CA / Covina'),
    ('MI', 'Portage', 'MI / Portage'),
    ('TX', 'Cedar Hill', 'TX / Cedar Hill'),
    ('CA', 'Ceres', 'CA / Ceres'),
    ('TX', 'Texas City', 'TX / Texas City'),
    ('ID', 'Twin Falls', 'ID / Twin Falls'),
    ('NM', 'Roswell', 'NM / Roswell'),
    ('WV', 'Huntington', 'WV / Huntington'),
    ('AL', 'Madison', 'AL / Madison'),
    ('WI', 'Wauwatosa', 'WI / Wauwatosa'),
    ('IN', 'Lawrence', 'IN / Lawrence'),
    ('NC', 'Kannapolis', 'NC / Kannapolis'),
    ('LA', 'Alexandria', 'LA / Alexandria'),
    ('FL', 'St. Cloud', 'FL / St. Cloud'),
    ('TX', 'Wylie', 'TX / Wylie'),
    ('CA', 'Palm Springs', 'CA / Palm Springs'),
    ('WA', 'Lacey', 'WA / Lacey'),
    ('MO', 'Chesterfield', 'MO / Chesterfield'),
    ('MI', 'Roseville', 'MI / Roseville'),
    ('CA', 'San Luis Obispo', 'CA / San Luis Obispo'),
    ('IL', 'Glenview', 'IL / Glenview'),
    ('CA', 'San Jacinto', 'CA / San Jacinto'),
    ('OH', 'Euclid', 'OH / Euclid'),
    ('NC', 'Apex', 'NC / Apex'),
    ('RI', 'East Providence', 'RI / East Providence'),
    ('KS', 'Salina', 'KS / Salina'),
    ('UT', 'Draper', 'UT / Draper'),
    ('IN', 'Jeffersonville', 'IN / Jeffersonville'),
    ('AR', 'Bentonville', 'AR / Bentonville'),
    ('CA', 'Lincoln', 'CA / Lincoln'),
    ('MS', 'Hattiesburg', 'MS / Hattiesburg'),
    ('VA', 'Charlottesville', 'VA / Charlottesville'),
    ('AZ', 'Maricopa', 'AZ / Maricopa'),
    ('IN', 'Columbus', 'IN / Columbus'),
    ('OH', 'Mentor', 'OH / Mentor'),
    ('OH', 'Mansfield', 'OH / Mansfield'),
    ('TX', 'Keller', 'TX / Keller'),
    ('CT', 'Middletown', 'CT / Middletown'),
    ('IL', 'Elmhurst', 'IL / Elmhurst'),
    ('OH', 'Beavercreek', 'OH / Beavercreek'),
    ('MA', 'Everett', 'MA / Everett'),
    ('CO', 'Littleton', 'CO / Littleton'),
    ('FL', 'Titusville', 'FL / Titusville'),
    ('MS', 'Biloxi', 'MS / Biloxi'),
    ('IN', 'West Lafayette', 'IN / West Lafayette'),
    ('CA', 'Newark', 'CA / Newark'),
    ('NY', 'Binghamton', 'NY / Binghamton'),
    ('OH', 'Dublin', 'OH / Dublin'),
    ('CA', 'Beaumont', 'CA / Beaumont'),
    ('FL', 'Fort Pierce', 'FL / Fort Pierce'),
    ('MT', 'Bozeman', 'MT / Bozeman'),
    ('VA', 'Blacksburg', 'VA / Blacksburg'),
    ('TX', 'Burleson', 'TX / Burleson'),
    ('CA', 'Coachella', 'CA / Coachella'),
    ('NJ', 'Sayreville', 'NJ / Sayreville'),
    ('FL', 'Ocoee', 'FL / Ocoee'),
    ('NJ', 'Hackensack', 'NJ / Hackensack'),
    ('FL', 'Cutler Bay', 'FL / Cutler Bay'),
    ('OH', 'Cleveland Heights', 'OH / Cleveland Heights'),
    ('OH', 'Strongsville', 'OH / Strongsville'),
    ('CA', 'Danville', 'CA / Danville'),
    ('PA', 'Altoona', 'PA / Altoona'),
    ('WA', 'Bothell', 'WA / Bothell'),
    ('MA', 'Attleboro', 'MA / Attleboro'),
    ('TX', 'Haltom City', 'TX / Haltom City'),
    ('FL', 'Oakland Park', 'FL / Oakland Park'),
    ('TN', 'Cleveland', 'TN / Cleveland'),
    ('MA', 'Barnstable Town', 'MA / Barnstable Town'),
    ('CA', 'El Centro', 'CA / El Centro'),
    ('CA', 'Morgan Hill', 'CA / Morgan Hill'),
    ('FL', 'North Miami Beach', 'FL / North Miami Beach'),
    ('PA', 'York', 'PA / York'),
    ('AR', 'Pine Bluff', 'AR / Pine Bluff'),
    ('IL', 'Lombard', 'IL / Lombard'),
    ('AZ', 'Oro Valley', 'AZ / Oro Valley'),
    ('CA', 'Lompoc', 'CA / Lompoc'),
    ('FL', 'North Lauderdale', 'FL / North Lauderdale'),
    ('TX', 'Rockwall', 'TX / Rockwall'),
    ('FL', 'Altamonte Springs', 'FL / Altamonte Springs'),
    ('AZ', 'Marana', 'AZ / Marana'),
    ('NY', 'Freeport', 'NY / Freeport'),
    ('AZ', 'Sierra Vista', 'AZ / Sierra Vista'),
    ('IL', 'DeKalb', 'IL / DeKalb'),
    ('AZ', 'Prescott Valley', 'AZ / Prescott Valley'),
    ('MA', 'Salem', 'MA / Salem'),
    ('IA', 'Urbandale', 'IA / Urbandale'),
    ('MO', 'Jefferson City', 'MO / Jefferson City'),
    ('CA', 'San Bruno', 'CA / San Bruno'),
    ('WI', 'Fond du Lac', 'WI / Fond du Lac'),
    ('IL', 'Plainfield', 'IL / Plainfield'),
    ('NH', 'Concord', 'NH / Concord'),
    ('MA', 'Pittsfield', 'MA / Pittsfield'),
    ('UT', 'Riverton', 'UT / Riverton'),
    ('CA', 'Bell Gardens', 'CA / Bell Gardens'),
    ('GA', 'Peachtree Corners', 'GA / Peachtree Corners'),
    ('TX', 'Leander', 'TX / Leander'),
    ('CA', 'Rohnert Park', 'CA / Rohnert Park'),
    ('OH', 'Fairfield', 'OH / Fairfield'),
    ('TN', 'Brentwood', 'TN / Brentwood'),
    ('AZ', 'Prescott', 'AZ / Prescott'),
    ('TX', 'Little Elm', 'TX / Little Elm'),
    ('MN', 'Moorhead', 'MN / Moorhead'),
    ('CA', 'Brea', 'CA / Brea'),
    ('NJ', 'Linden', 'NJ / Linden'),
    ('CA', 'Rancho Palos Verdes', 'CA / Rancho Palos Verdes'),
    ('TX', 'The Colony', 'TX / The Colony'),
    ('VT', 'Burlington', 'VT / Burlington'),
    ('IL', 'Moline', 'IL / Moline'),
    ('FL', 'Ormond Beach', 'FL / Ormond Beach'),
    ('NJ', 'Kearny', 'NJ / Kearny'),
    ('MI', 'Midland', 'MI / Midland'),
    ('SC', 'Goose Creek', 'SC / Goose Creek'),
    ('IL', 'Urbana', 'IL / Urbana'),
    ('PA', 'State College', 'PA / State College'),
    ('FL', 'Winter Garden', 'FL / Winter Garden'),
    ('IL', 'Belleville', 'IL / Belleville'),
    ('VA', 'Danville', 'VA / Danville'),
    ('WA', 'Edmonds', 'WA / Edmonds'),
    ('MN', 'Mankato', 'MN / Mankato'),
    ('MA', 'Leominster', 'MA / Leominster'),
    ('NM', 'Farmington', 'NM / Farmington'),
    ('TX', 'Sherman', 'TX / Sherman'),
    ('MA', 'Westfield', 'MA / Westfield'),
    ('VA', 'Manassas', 'VA / Manassas'),
    ('OH', 'Findlay', 'OH / Findlay'),
    ('RI', 'Woonsocket', 'RI / Woonsocket'),
    ('IA', 'Cedar Falls', 'IA / Cedar Falls'),
    ('MA', 'Beverly', 'MA / Beverly'),
    ('TX', 'Coppell', 'TX / Coppell'),
    ('IL', 'Buffalo Grove', 'IL / Buffalo Grove'),
    ('CT', 'Shelton', 'CT / Shelton'),
    ('KS', 'Hutchinson', 'KS / Hutchinson'),
    ('TX', 'Huntsville', 'TX / Huntsville'),
    ('IL', 'Bartlett', 'IL / Bartlett'),
    ('CA', 'La Quinta', 'CA / La Quinta'),
    ('CA', 'Campbell', 'CA / Campbell'),
    ('KY', 'Covington', 'KY / Covington'),
    ('SC', 'Sumter', 'SC / Sumter'),
    ('WA', 'Bremerton', 'WA / Bremerton'),
    ('WA', 'Puyallup', 'WA / Puyallup'),
    ('CA', 'Oakley', 'CA / Oakley'),
    ('MN', 'Shakopee', 'MN / Shakopee'),
    ('PA', 'Wilkes-Barre', 'PA / Wilkes-Barre'),
    ('NC', 'Hickory', 'NC / Hickory'),
    ('IL', 'Quincy', 'IL / Quincy'),
    ('SC', 'Hilton Head Island', 'SC / Hilton Head Island'),
    ('MD', 'Hagerstown', 'MD / Hagerstown'),
    ('MA', 'Fitchburg', 'MA / Fitchburg'),
    ('CA', 'San Gabriel', 'CA / San Gabriel'),
    ('CA', 'La Puente', 'CA / La Puente'),
    ('IL', 'Crystal Lake', 'IL / Crystal Lake'),
    ('MA', 'Holyoke', 'MA / Holyoke'),
    ('CA', 'Calexico', 'CA / Calexico'),
    ('IL', 'Streamwood', 'IL / Streamwood'),
    ('MN', 'Maplewood', 'MN / Maplewood'),
    ('NC', 'Wake Forest', 'NC / Wake Forest'),
    ('IL', 'Carol Stream', 'IL / Carol Stream'),
    ('TX', 'Weslaco', 'TX / Weslaco'),
    ('FL', 'Greenacres', 'FL / Greenacres'),
    ('GA', 'Gainesville', 'GA / Gainesville'),
    ('AZ', 'Bullhead City', 'AZ / Bullhead City'),
    ('AL', 'Florence', 'AL / Florence'),
    ('AZ', 'Apache Junction', 'AZ / Apache Junction'),
    ('OH', 'Warren', 'OH / Warren'),
    ('OH', 'Lancaster', 'OH / Lancaster'),
    ('WI', 'New Berlin', 'WI / New Berlin'),
    ('OH', 'Grove City', 'OH / Grove City'),
    ('IL', 'Romeoville', 'IL / Romeoville'),
    ('MA', 'Chelsea', 'MA / Chelsea'),
    ('MA', 'Marlborough', 'MA / Marlborough'),
    ('MO', 'Cape Girardeau', 'MO / Cape Girardeau'),
    ('CT', 'Norwich', 'CT / Norwich'),
    ('FL', 'Hallandale Beach', 'FL / Hallandale Beach'),
    ('TX', 'Duncanville', 'TX / Duncanville'),
    ('TX', 'Schertz', 'TX / Schertz'),
    ('MA', 'Woburn', 'MA / Woburn'),
    ('MD', 'Annapolis', 'MD / Annapolis'),
    ('TX', 'Friendswood', 'TX / Friendswood'),
    ('NM', 'Clovis', 'NM / Clovis'),
    ('CA', 'Culver City', 'CA / Culver City'),
    ('FL', 'Oviedo', 'FL / Oviedo'),
    ('TX', 'Hurst', 'TX / Hurst'),
    ('MS', 'Meridian', 'MS / Meridian'),
    ('CA', 'Pacifica', 'CA / Pacifica'),
    ('TN', 'Germantown', 'TN / Germantown'),
    ('OH', 'Westerville', 'OH / Westerville'),
    ('CO', 'Northglenn', 'CO / Northglenn'),
    ('OR', 'Keizer', 'OR / Keizer'),
    ('FL', 'Winter Haven', 'FL / Winter Haven'),
    ('OR', 'Lake Oswego', 'OR / Lake Oswego'),
    ('CA', 'Montclair', 'CA / Montclair'),
    ('WI', 'Wausau', 'WI / Wausau'),
    ('TX', 'Lancaster', 'TX / Lancaster'),
    ('UT', 'Spanish Fork', 'UT / Spanish Fork'),
    ('MS', 'Tupelo', 'MS / Tupelo'),
    ('UT', 'Pleasant Grove', 'UT / Pleasant Grove'),
    ('NJ', 'Atlantic City', 'NJ / Atlantic City'),
    ('CA', 'Stanton', 'CA / Stanton'),
    ('OH', 'Delaware', 'OH / Delaware'),
    ('IA', 'Marion', 'IA / Marion'),
    ('GA', 'Milton', 'GA / Milton'),
    ('OK', 'Muskogee', 'OK / Muskogee'),
    ('MI', 'Muskegon', 'MI / Muskegon'),
    ('SC', 'Florence', 'SC / Florence'),
    ('IL', 'Wheeling', 'IL / Wheeling'),
    ('CO', 'Brighton', 'CO / Brighton'),
    ('IL', 'Carpentersville', 'IL / Carpentersville'),
    ('CA', 'Martinez', 'CA / Martinez'),
    ('NC', 'Indian Trail', 'NC / Indian Trail'),
    ('IL', 'Rock Island', 'IL / Rock Island'),
    ('UT', 'Roy', 'UT / Roy'),
    ('FL', 'Plant City', 'FL / Plant City');