drop table if exists location;

CREATE TABLE location (
    id    BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    state varchar,
    city  VARCHAR,
    name  VARCHAR,
    CONSTRAINT city_should_have_state CHECK (state IS NOT NULL OR city IS NULL),
    CONSTRAINT state_should_have_name CHECK (city IS NOT NULL OR name IS NOT NULL),
    CONSTRAINT city_should_not_have_name CHECK (city IS NULL OR name IS NULL),
    CONSTRAINT unique_state_city UNIQUE (state, city) -- Add "NULLS NOT DISTINCT" in Postgres 15
);

INSERT INTO location(state, city, name)
VALUES (NULL, NULL, 'United States'),
    ('AL', NULL, 'Alabama'),
    ('AK', NULL, 'Alaska'),
    ('AZ', NULL, 'Arizona'),
    ('AR', NULL, 'Arkansas'),
    ('CA', NULL, 'California'),
    ('CO', NULL, 'Colorado'),
    ('CT', NULL, 'Connecticut'),
    ('DE', NULL, 'Delaware'),
    ('DC', NULL, 'District of Columbia'),
    ('FL', NULL, 'Florida'),
    ('GA', NULL, 'Georgia'),
    ('HI', NULL, 'Hawaii'),
    ('ID', NULL, 'Idaho'),
    ('IL', NULL, 'Illinois'),
    ('IN', NULL, 'Indiana'),
    ('IA', NULL, 'Iowa'),
    ('KS', NULL, 'Kansas'),
    ('KY', NULL, 'Kentucky'),
    ('LA', NULL, 'Louisiana'),
    ('ME', NULL, 'Maine'),
    ('MD', NULL, 'Maryland'),
    ('MA', NULL, 'Massachusetts'),
    ('MI', NULL, 'Michigan'),
    ('MN', NULL, 'Minnesota'),
    ('MS', NULL, 'Mississippi'),
    ('MO', NULL, 'Missouri'),
    ('MT', NULL, 'Montana'),
    ('NE', NULL, 'Nebraska'),
    ('NV', NULL, 'Nevada'),
    ('NH', NULL, 'New Hampshire'),
    ('NJ', NULL, 'New Jersey'),
    ('NM', NULL, 'New Mexico'),
    ('NY', NULL, 'New York'),
    ('NC', NULL, 'North Carolina'),
    ('ND', NULL, 'North Dakota'),
    ('OH', NULL, 'Ohio'),
    ('OK', NULL, 'Oklahoma'),
    ('OR', NULL, 'Oregon'),
    ('PA', NULL, 'Pennsylvania'),
    ('RI', NULL, 'Rhode Island'),
    ('SC', NULL, 'South Carolina'),
    ('SD', NULL, 'South Dakota'),
    ('TN', NULL, 'Tennessee'),
    ('TX', NULL, 'Texas'),
    ('UT', NULL, 'Utah'),
    ('VT', NULL, 'Vermont'),
    ('VA', NULL, 'Virginia'),
    ('WA', NULL, 'Washington'),
    ('WV', NULL, 'West Virginia'),
    ('WI', NULL, 'Wisconsin'),
    ('WY', NULL, 'Wyoming'),
    ('IA', 'Ankeny', NULL),
    ('UT', 'Bountiful', NULL),
    ('NY', 'New York', NULL),
    ('CA', 'Los Angeles', NULL),
    ('IL', 'Chicago', NULL),
    ('TX', 'Houston', NULL),
    ('AZ', 'Phoenix', NULL),
    ('PA', 'Philadelphia', NULL),
    ('TX', 'San Antonio', NULL),
    ('CA', 'San Diego', NULL),
    ('TX', 'Dallas', NULL),
    ('CA', 'San Jose', NULL),
    ('TX', 'Austin', NULL),
    ('FL', 'Jacksonville', NULL),
    ('CA', 'San Francisco', NULL),
    ('OH', 'Columbus', NULL),
    ('IN', 'Indianapolis', NULL),
    ('TX', 'Fort Worth', NULL),
    ('NC', 'Charlotte', NULL),
    ('WA', 'Seattle', NULL),
    ('CO', 'Denver', NULL),
    ('TX', 'El Paso', NULL),
    ('DC', 'Washington', NULL),
    ('MA', 'Boston', NULL),
    ('MI', 'Detroit', NULL),
    ('TN', 'Nashville-Davidson', NULL),
    ('TN', 'Memphis', NULL),
    ('OR', 'Portland', NULL),
    ('OK', 'Oklahoma City', NULL),
    ('NV', 'Las Vegas', NULL),
    ('KY', 'Louisville/Jefferson County', NULL),
    ('MD', 'Baltimore', NULL),
    ('WI', 'Milwaukee', NULL),
    ('NM', 'Albuquerque', NULL),
    ('AZ', 'Tucson', NULL),
    ('CA', 'Fresno', NULL),
    ('CA', 'Sacramento', NULL),
    ('AZ', 'Mesa', NULL),
    ('MO', 'Kansas City', NULL),
    ('GA', 'Atlanta', NULL),
    ('CA', 'Long Beach', NULL),
    ('CO', 'Colorado Springs', NULL),
    ('NC', 'Raleigh', NULL),
    ('FL', 'Miami', NULL),
    ('VA', 'Virginia Beach', NULL),
    ('NE', 'Omaha', NULL),
    ('CA', 'Oakland', NULL),
    ('MN', 'Minneapolis', NULL),
    ('OK', 'Tulsa', NULL),
    ('TX', 'Arlington', NULL),
    ('LA', 'New Orleans', NULL),
    ('KS', 'Wichita', NULL),
    ('OH', 'Cleveland', NULL),
    ('FL', 'Tampa', NULL),
    ('CA', 'Bakersfield', NULL),
    ('CO', 'Aurora', NULL),
    ('HI', 'Honolulu', NULL),
    ('CA', 'Anaheim', NULL),
    ('CA', 'Santa Ana', NULL),
    ('TX', 'Corpus Christi', NULL),
    ('CA', 'Riverside', NULL),
    ('KY', 'Lexington-Fayette', NULL),
    ('MO', 'St. Louis', NULL),
    ('CA', 'Stockton', NULL),
    ('PA', 'Pittsburgh', NULL),
    ('MN', 'St. Paul', NULL),
    ('OH', 'Cincinnati', NULL),
    ('AK', 'Anchorage', NULL),
    ('NV', 'Henderson', NULL),
    ('NC', 'Greensboro', NULL),
    ('TX', 'Plano', NULL),
    ('NJ', 'Newark', NULL),
    ('NE', 'Lincoln', NULL),
    ('OH', 'Toledo', NULL),
    ('FL', 'Orlando', NULL),
    ('CA', 'Chula Vista', NULL),
    ('CA', 'Irvine', NULL),
    ('IN', 'Fort Wayne', NULL),
    ('NJ', 'Jersey City', NULL),
    ('NC', 'Durham', NULL),
    ('FL', 'St. Petersburg', NULL),
    ('TX', 'Laredo', NULL),
    ('NY', 'Buffalo', NULL),
    ('WI', 'Madison', NULL),
    ('TX', 'Lubbock', NULL),
    ('AZ', 'Chandler', NULL),
    ('AZ', 'Scottsdale', NULL),
    ('AZ', 'Glendale', NULL),
    ('NV', 'Reno', NULL),
    ('TX', 'Kyle', NULL),
    ('VA', 'Norfolk', NULL),
    ('NC', 'Winston-Salem', NULL),
    ('NV', 'North Las Vegas', NULL),
    ('TX', 'Irving', NULL),
    ('VA', 'Chesapeake', NULL),
    ('AZ', 'Gilbert', NULL),
    ('FL', 'Hialeah', NULL),
    ('TX', 'Garland', NULL),
    ('CA', 'Fremont', NULL),
    ('LA', 'Baton Rouge', NULL),
    ('VA', 'Richmond', NULL),
    ('ID', 'Boise City', NULL),
    ('CA', 'San Bernardino', NULL),
    ('WA', 'Spokane', NULL),
    ('IA', 'Des Moines', NULL),
    ('CA', 'Modesto', NULL),
    ('AL', 'Birmingham', NULL),
    ('WA', 'Tacoma', NULL),
    ('CA', 'Fontana', NULL),
    ('NY', 'Rochester', NULL),
    ('CA', 'Oxnard', NULL),
    ('CA', 'Moreno Valley', NULL),
    ('NC', 'Fayetteville', NULL),
    ('IL', 'Aurora', NULL),
    ('CA', 'Glendale', NULL),
    ('NY', 'Yonkers', NULL),
    ('CA', 'Huntington Beach', NULL),
    ('AL', 'Montgomery', NULL),
    ('TX', 'Amarillo', NULL),
    ('AR', 'Little Rock', NULL),
    ('OH', 'Akron', NULL),
    ('GA', 'Columbus', NULL),
    ('GA', 'Augusta-Richmond County', NULL),
    ('MI', 'Grand Rapids', NULL),
    ('LA', 'Shreveport', NULL),
    ('UT', 'Salt Lake City', NULL),
    ('AL', 'Huntsville', NULL),
    ('AL', 'Mobile', NULL),
    ('FL', 'Tallahassee', NULL),
    ('TX', 'Grand Prairie', NULL),
    ('KS', 'Overland Park', NULL),
    ('TN', 'Knoxville', NULL),
    ('FL', 'Port St. Lucie', NULL),
    ('MA', 'Worcester', NULL),
    ('TX', 'Brownsville', NULL),
    ('AZ', 'Tempe', NULL),
    ('CA', 'Santa Clarita', NULL),
    ('VA', 'Newport News', NULL),
    ('FL', 'Cape Coral', NULL),
    ('RI', 'Providence', NULL),
    ('FL', 'Fort Lauderdale', NULL),
    ('TN', 'Chattanooga', NULL),
    ('CA', 'Rancho Cucamonga', NULL),
    ('CA', 'Oceanside', NULL),
    ('CA', 'Santa Rosa', NULL),
    ('CA', 'Garden Grove', NULL),
    ('WA', 'Vancouver', NULL),
    ('SD', 'Sioux Falls', NULL),
    ('CA', 'Ontario', NULL),
    ('TX', 'McKinney', NULL),
    ('CA', 'Elk Grove', NULL),
    ('MS', 'Jackson', NULL),
    ('FL', 'Pembroke Pines', NULL),
    ('OR', 'Salem', NULL),
    ('MO', 'Springfield', NULL),
    ('CA', 'Corona', NULL),
    ('OR', 'Eugene', NULL),
    ('CO', 'Fort Collins', NULL),
    ('AZ', 'Peoria', NULL),
    ('TX', 'Frisco', NULL),
    ('NC', 'Cary', NULL),
    ('CA', 'Lancaster', NULL),
    ('CA', 'Hayward', NULL),
    ('CA', 'Palmdale', NULL),
    ('CA', 'Salinas', NULL),
    ('VA', 'Alexandria', NULL),
    ('CO', 'Lakewood', NULL),
    ('MA', 'Springfield', NULL),
    ('TX', 'Pasadena', NULL),
    ('CA', 'Sunnyvale', NULL),
    ('GA', 'Macon-Bibb County', NULL),
    ('CA', 'Pomona', NULL),
    ('FL', 'Hollywood', NULL),
    ('KS', 'Kansas City', NULL),
    ('CA', 'Escondido', NULL),
    ('TN', 'Clarksville', NULL),
    ('IL', 'Joliet', NULL),
    ('IL', 'Rockford', NULL),
    ('CA', 'Torrance', NULL),
    ('IL', 'Naperville', NULL),
    ('NJ', 'Paterson', NULL),
    ('GA', 'Savannah', NULL),
    ('CT', 'Bridgeport', NULL),
    ('TX', 'Mesquite', NULL),
    ('TX', 'Killeen', NULL),
    ('NY', 'Syracuse', NULL),
    ('TX', 'McAllen', NULL),
    ('CA', 'Pasadena', NULL),
    ('WA', 'Bellevue', NULL),
    ('CA', 'Fullerton', NULL),
    ('CA', 'Orange', NULL),
    ('OH', 'Dayton', NULL),
    ('FL', 'Miramar', NULL),
    ('CO', 'Thornton', NULL),
    ('UT', 'West Valley City', NULL),
    ('KS', 'Olathe', NULL),
    ('VA', 'Hampton', NULL),
    ('MI', 'Warren', NULL),
    ('TX', 'Midland', NULL),
    ('TX', 'Waco', NULL),
    ('SC', 'Charleston', NULL),
    ('SC', 'Columbia', NULL),
    ('TX', 'Denton', NULL),
    ('TX', 'Carrollton', NULL),
    ('AZ', 'Surprise', NULL),
    ('CA', 'Roseville', NULL),
    ('MI', 'Sterling Heights', NULL),
    ('TN', 'Murfreesboro', NULL),
    ('FL', 'Gainesville', NULL),
    ('IA', 'Cedar Rapids', NULL),
    ('CA', 'Visalia', NULL),
    ('FL', 'Coral Springs', NULL),
    ('CT', 'New Haven', NULL),
    ('CT', 'Stamford', NULL),
    ('CA', 'Thousand Oaks', NULL),
    ('CA', 'Concord', NULL),
    ('NJ', 'Elizabeth', NULL),
    ('LA', 'Lafayette', NULL),
    ('WA', 'Kent', NULL),
    ('KS', 'Topeka', NULL),
    ('CA', 'Simi Valley', NULL),
    ('CA', 'Santa Clara', NULL),
    ('GA', 'Athens-Clarke County', NULL),
    ('CT', 'Hartford', NULL),
    ('CA', 'Victorville', NULL),
    ('TX', 'Abilene', NULL),
    ('OK', 'Norman', NULL),
    ('CA', 'Vallejo', NULL),
    ('CA', 'Berkeley', NULL),
    ('TX', 'Round Rock', NULL),
    ('MI', 'Ann Arbor', NULL),
    ('ND', 'Fargo', NULL),
    ('MO', 'Columbia', NULL),
    ('PA', 'Allentown', NULL),
    ('IN', 'Evansville', NULL),
    ('TX', 'Beaumont', NULL),
    ('TX', 'Odessa', NULL),
    ('NC', 'Wilmington', NULL),
    ('CO', 'Arvada', NULL),
    ('MO', 'Independence', NULL),
    ('UT', 'Provo', NULL),
    ('MI', 'Lansing', NULL),
    ('CA', 'El Monte', NULL),
    ('IL', 'Springfield', NULL),
    ('CA', 'Fairfield', NULL),
    ('FL', 'Clearwater', NULL),
    ('IL', 'Peoria', NULL),
    ('MN', 'Rochester', NULL),
    ('CA', 'Carlsbad', NULL),
    ('CO', 'Westminster', NULL),
    ('UT', 'West Jordan', NULL),
    ('TX', 'Pearland', NULL),
    ('TX', 'Richardson', NULL),
    ('CA', 'Downey', NULL),
    ('FL', 'Miami Gardens', NULL),
    ('CA', 'Temecula', NULL),
    ('CA', 'Costa Mesa', NULL),
    ('TX', 'College Station', NULL),
    ('IL', 'Elgin', NULL),
    ('CA', 'Murrieta', NULL),
    ('OR', 'Gresham', NULL),
    ('NC', 'High Point', NULL),
    ('CA', 'Antioch', NULL),
    ('CA', 'Inglewood', NULL),
    ('MA', 'Cambridge', NULL),
    ('MA', 'Lowell', NULL),
    ('NH', 'Manchester', NULL),
    ('MT', 'Billings', NULL),
    ('CO', 'Pueblo', NULL),
    ('FL', 'Palm Bay', NULL),
    ('CO', 'Centennial', NULL),
    ('CA', 'Richmond', NULL),
    ('CA', 'San Buenaventura (Ventura)', NULL),
    ('FL', 'Pompano Beach', NULL),
    ('SC', 'North Charleston', NULL),
    ('WA', 'Everett', NULL),
    ('CT', 'Waterbury', NULL),
    ('FL', 'West Palm Beach', NULL),
    ('CO', 'Boulder', NULL),
    ('CA', 'West Covina', NULL),
    ('OK', 'Broken Arrow', NULL),
    ('CA', 'Clovis', NULL),
    ('CA', 'Daly City', NULL),
    ('FL', 'Lakeland', NULL),
    ('CA', 'Santa Maria', NULL),
    ('CA', 'Norwalk', NULL),
    ('GA', 'Sandy Springs', NULL),
    ('OR', 'Hillsboro', NULL),
    ('WI', 'Green Bay', NULL),
    ('TX', 'Tyler', NULL),
    ('TX', 'Wichita Falls', NULL),
    ('TX', 'Lewisville', NULL),
    ('CA', 'Burbank', NULL),
    ('CO', 'Greeley', NULL),
    ('CA', 'San Mateo', NULL),
    ('CA', 'El Cajon', NULL),
    ('CA', 'Jurupa Valley', NULL),
    ('CA', 'Rialto', NULL),
    ('IA', 'Davenport', NULL),
    ('TX', 'League City', NULL),
    ('FL', 'Davie', NULL),
    ('NM', 'Las Cruces', NULL),
    ('IN', 'South Bend', NULL),
    ('CA', 'Vista', NULL),
    ('WA', 'Renton', NULL),
    ('TX', 'San Angelo', NULL),
    ('VA', 'Roanoke', NULL),
    ('WI', 'Kenosha', NULL),
    ('AL', 'Tuscaloosa', NULL),
    ('TX', 'Allen', NULL),
    ('PA', 'Erie', NULL),
    ('NV', 'Sparks', NULL),
    ('CA', 'Vacaville', NULL),
    ('NY', 'Albany', NULL),
    ('OR', 'Beaverton', NULL),
    ('CA', 'Compton', NULL),
    ('UT', 'Orem', NULL),
    ('MI', 'Flint', NULL),
    ('WA', 'Federal Way', NULL),
    ('CA', 'Mission Viejo', NULL),
    ('WA', 'Spokane Valley', NULL),
    ('FL', 'Boca Raton', NULL),
    ('MO', 'Lee''s Summit', NULL),
    ('NM', 'Rio Rancho', NULL),
    ('UT', 'Sandy', NULL),
    ('MA', 'Brockton', NULL),
    ('ID', 'Meridian', NULL),
    ('CA', 'South Gate', NULL),
    ('KS', 'Lawrence', NULL),
    ('CA', 'San Marcos', NULL),
    ('VA', 'Portsmouth', NULL),
    ('MA', 'New Bedford', NULL),
    ('AZ', 'Yuma', NULL),
    ('OK', 'Lawton', NULL),
    ('GA', 'Roswell', NULL),
    ('MI', 'Dearborn', NULL),
    ('MI', 'Livonia', NULL),
    ('WA', 'Yakima', NULL),
    ('FL', 'Sunrise', NULL),
    ('CA', 'Hesperia', NULL),
    ('MA', 'Quincy', NULL),
    ('CO', 'Longmont', NULL),
    ('CA', 'Carson', NULL),
    ('FL', 'Plantation', NULL),
    ('MA', 'Lynn', NULL),
    ('CA', 'Santa Monica', NULL),
    ('CA', 'Santa Barbara', NULL),
    ('FL', 'Miami Beach', NULL),
    ('CA', 'Redding', NULL),
    ('CA', 'Chico', NULL),
    ('CA', 'Westminster', NULL),
    ('NC', 'Greenville', NULL),
    ('ID', 'Nampa', NULL),
    ('OK', 'Edmond', NULL),
    ('OR', 'Bend', NULL),
    ('IN', 'Carmel', NULL),
    ('CA', 'San Leandro', NULL),
    ('IN', 'Fishers', NULL),
    ('FL', 'Deltona', NULL),
    ('NC', 'Concord', NULL),
    ('CA', 'Tracy', NULL),
    ('VA', 'Suffolk', NULL),
    ('NC', 'Asheville', NULL),
    ('CA', 'Livermore', NULL),
    ('MA', 'Newton', NULL),
    ('MA', 'Fall River', NULL),
    ('CA', 'Menifee', NULL),
    ('CA', 'Indio', NULL),
    ('CT', 'Norwalk', NULL),
    ('IL', 'Waukegan', NULL),
    ('TX', 'Sugar Land', NULL),
    ('AR', 'Fort Smith', NULL),
    ('CA', 'Hawthorne', NULL),
    ('NH', 'Nashua', NULL),
    ('CA', 'Chino', NULL),
    ('WA', 'Kirkland', NULL),
    ('TX', 'Edinburg', NULL),
    ('PA', 'Reading', NULL),
    ('WA', 'Bellingham', NULL),
    ('CA', 'Citrus Heights', NULL),
    ('CA', 'Whittier', NULL),
    ('UT', 'Ogden', NULL),
    ('CA', 'Newport Beach', NULL),
    ('IL', 'Champaign', NULL),
    ('MN', 'Duluth', NULL),
    ('MO', 'O''Fallon', NULL),
    ('NJ', 'Clifton', NULL),
    ('CA', 'Alhambra', NULL),
    ('MN', 'Bloomington', NULL),
    ('FL', 'Palm Coast', NULL),
    ('CT', 'Danbury', NULL),
    ('AL', 'Hoover', NULL),
    ('CA', 'Redwood City', NULL),
    ('IN', 'Bloomington', NULL),
    ('CA', 'Hemet', NULL),
    ('SC', 'Mount Pleasant', NULL),
    ('NJ', 'Trenton', NULL),
    ('NM', 'Santa Fe', NULL),
    ('GA', 'Johns Creek', NULL),
    ('AR', 'Fayetteville', NULL),
    ('MI', 'Troy', NULL),
    ('TX', 'Mission', NULL),
    ('TX', 'Bryan', NULL),
    ('CA', 'Lake Forest', NULL),
    ('CA', 'Buena Park', NULL),
    ('FL', 'Largo', NULL),
    ('IL', 'Cicero', NULL),
    ('AZ', 'Avondale', NULL),
    ('IA', 'Sioux City', NULL),
    ('CA', 'Merced', NULL),
    ('UT', 'St. George', NULL),
    ('TX', 'Conroe', NULL),
    ('CA', 'Pleasanton', NULL),
    ('TX', 'Longview', NULL),
    ('OR', 'Medford', NULL),
    ('RI', 'Warwick', NULL),
    ('MI', 'Westland', NULL),
    ('MA', 'Somerville', NULL),
    ('FL', 'Melbourne', NULL),
    ('CA', 'Lakewood', NULL),
    ('MI', 'Farmington Hills', NULL),
    ('RI', 'Cranston', NULL),
    ('WA', 'Kennewick', NULL),
    ('CA', 'Mountain View', NULL),
    ('CA', 'Napa', NULL),
    ('CA', 'Tustin', NULL),
    ('VA', 'Lynchburg', NULL),
    ('MA', 'Lawrence', NULL),
    ('FL', 'Deerfield Beach', NULL),
    ('MN', 'Brooklyn Park', NULL),
    ('NY', 'New Rochelle', NULL),
    ('OH', 'Parma', NULL),
    ('CA', 'Alameda', NULL),
    ('CA', 'Chino Hills', NULL),
    ('AR', 'Springdale', NULL),
    ('IL', 'Bloomington', NULL),
    ('CA', 'Bellflower', NULL),
    ('WI', 'Racine', NULL),
    ('CA', 'Milpitas', NULL),
    ('WA', 'Auburn', NULL),
    ('TX', 'Pharr', NULL),
    ('PA', 'Scranton', NULL),
    ('CA', 'Folsom', NULL),
    ('AZ', 'Goodyear', NULL),
    ('MN', 'Plymouth', NULL),
    ('FL', 'Fort Myers', NULL),
    ('IN', 'Hammond', NULL),
    ('CA', 'Manteca', NULL),
    ('CO', 'Loveland', NULL),
    ('LA', 'Lake Charles', NULL),
    ('CA', 'Upland', NULL),
    ('MO', 'St. Joseph', NULL),
    ('CA', 'Baldwin Park', NULL),
    ('IN', 'Gary', NULL),
    ('CA', 'Perris', NULL),
    ('TX', 'Baytown', NULL),
    ('MI', 'Kalamazoo', NULL),
    ('UT', 'Layton', NULL),
    ('CA', 'San Ramon', NULL),
    ('FL', 'Boynton Beach', NULL),
    ('MI', 'Wyoming', NULL),
    ('NC', 'Gastonia', NULL),
    ('IL', 'Arlington Heights', NULL),
    ('CA', 'Union City', NULL),
    ('PA', 'Bethlehem', NULL),
    ('IL', 'Evanston', NULL),
    ('AR', 'Jonesboro', NULL),
    ('TN', 'Franklin', NULL),
    ('TX', 'Missouri City', NULL),
    ('IL', 'Bolingbrook', NULL),
    ('IL', 'Schaumburg', NULL),
    ('NJ', 'Camden', NULL),
    ('IA', 'Iowa City', NULL),
    ('GA', 'Warner Robins', NULL),
    ('WI', 'Appleton', NULL),
    ('SD', 'Rapid City', NULL),
    ('TX', 'New Braunfels', NULL),
    ('GA', 'Albany', NULL),
    ('TX', 'Temple', NULL),
    ('TX', 'Flower Mound', NULL),
    ('MI', 'Rochester Hills', NULL),
    ('MI', 'Southfield', NULL),
    ('SC', 'Rock Hill', NULL),
    ('CA', 'Turlock', NULL),
    ('IL', 'Decatur', NULL),
    ('CT', 'New Britain', NULL),
    ('CA', 'Apple Valley', NULL),
    ('ND', 'Bismarck', NULL),
    ('MT', 'Missoula', NULL),
    ('WI', 'Waukesha', NULL),
    ('CA', 'Rancho Cordova', NULL),
    ('MS', 'Gulfport', NULL),
    ('IN', 'Lafayette', NULL),
    ('FL', 'Lauderhill', NULL),
    ('AZ', 'Flagstaff', NULL),
    ('DE', 'Wilmington', NULL),
    ('RI', 'Pawtucket', NULL),
    ('OH', 'Canton', NULL),
    ('CA', 'Redlands', NULL),
    ('CA', 'Lynwood', NULL),
    ('CA', 'Pittsburg', NULL),
    ('NJ', 'Passaic', NULL),
    ('WA', 'Pasco', NULL),
    ('MD', 'Frederick', NULL),
    ('FL', 'Weston', NULL),
    ('TX', 'North Richland Hills', NULL),
    ('MN', 'Maple Grove', NULL),
    ('FL', 'Kissimmee', NULL),
    ('NJ', 'Union City', NULL),
    ('MO', 'St. Charles', NULL),
    ('CA', 'Walnut Creek', NULL),
    ('UT', 'South Jordan', NULL),
    ('IN', 'Muncie', NULL),
    ('TX', 'Cedar Park', NULL),
    ('MN', 'Woodbury', NULL),
    ('IL', 'Palatine', NULL),
    ('LA', 'Bossier City', NULL),
    ('AL', 'Dothan', NULL),
    ('NY', 'Mount Vernon', NULL),
    ('WI', 'Eau Claire', NULL),
    ('CA', 'Yorba Linda', NULL),
    ('CA', 'Davis', NULL),
    ('FL', 'Homestead', NULL),
    ('IA', 'Waterloo', NULL),
    ('CA', 'Redondo Beach', NULL),
    ('NC', 'Jacksonville', NULL),
    ('MD', 'Gaithersburg', NULL),
    ('TX', 'Victoria', NULL),
    ('MN', 'St. Cloud', NULL),
    ('WA', 'Marysville', NULL),
    ('SC', 'Greenville', NULL),
    ('FL', 'Delray Beach', NULL),
    ('CA', 'Camarillo', NULL),
    ('TX', 'Georgetown', NULL),
    ('LA', 'Kenner', NULL),
    ('CA', 'Palo Alto', NULL),
    ('TN', 'Jackson', NULL),
    ('CA', 'South San Francisco', NULL),
    ('MD', 'Rockville', NULL),
    ('ME', 'Portland', NULL),
    ('CA', 'Yuba City', NULL),
    ('TN', 'Johnson City', NULL),
    ('FL', 'Daytona Beach', NULL),
    ('WI', 'Oshkosh', NULL),
    ('CO', 'Broomfield', NULL),
    ('MN', 'Eagan', NULL),
    ('AR', 'North Little Rock', NULL),
    ('NJ', 'Bayonne', NULL),
    ('IA', 'Ames', NULL),
    ('TX', 'Mansfield', NULL),
    ('TX', 'Harlingen', NULL),
    ('GA', 'Alpharetta', NULL),
    ('CA', 'Laguna Niguel', NULL),
    ('CA', 'San Clemente', NULL),
    ('AR', 'Conway', NULL),
    ('KY', 'Bowling Green', NULL),
    ('FL', 'Tamarac', NULL),
    ('KS', 'Shawnee', NULL),
    ('AR', 'Rogers', NULL),
    ('NY', 'Schenectady', NULL),
    ('NJ', 'East Orange', NULL),
    ('CA', 'Lodi', NULL),
    ('AZ', 'Buckeye', NULL),
    ('IA', 'West Des Moines', NULL),
    ('CA', 'Santa Cruz', NULL),
    ('CA', 'Madera', NULL),
    ('OH', 'Youngstown', NULL),
    ('FL', 'North Port', NULL),
    ('IL', 'Skokie', NULL),
    ('CA', 'Lake Elsinore', NULL),
    ('WI', 'Janesville', NULL),
    ('WY', 'Cheyenne', NULL),
    ('MN', 'Eden Prairie', NULL),
    ('FL', 'Wellington', NULL),
    ('FL', 'Jupiter', NULL),
    ('WA', 'Sammamish', NULL),
    ('OH', 'Lorain', NULL),
    ('CA', 'Pico Rivera', NULL),
    ('CA', 'Montebello', NULL),
    ('CA', 'Encinitas', NULL),
    ('AL', 'Auburn', NULL),
    ('MA', 'Waltham', NULL),
    ('MN', 'Blaine', NULL),
    ('MA', 'Haverhill', NULL),
    ('CA', 'Rocklin', NULL),
    ('CA', 'Tulare', NULL),
    ('IA', 'Council Bluffs', NULL),
    ('WA', 'Redmond', NULL),
    ('MN', 'Coon Rapids', NULL),
    ('FL', 'North Miami', NULL),
    ('OH', 'Hamilton', NULL),
    ('TX', 'Rowlett', NULL),
    ('TX', 'San Marcos', NULL),
    ('MN', 'Lakeville', NULL),
    ('OR', 'Springfield', NULL),
    ('CO', 'Grand Junction', NULL),
    ('CA', 'La Habra', NULL),
    ('OK', 'Moore', NULL),
    ('MN', 'Burnsville', NULL),
    ('MI', 'Taylor', NULL),
    ('CA', 'Eastvale', NULL),
    ('CA', 'National City', NULL),
    ('UT', 'Lehi', NULL),
    ('FL', 'Port Orange', NULL),
    ('CA', 'Monterey Park', NULL),
    ('GA', 'Marietta', NULL),
    ('IN', 'Terre Haute', NULL),
    ('MA', 'Malden', NULL),
    ('WA', 'Lakewood', NULL),
    ('NY', 'Utica', NULL),
    ('CA', 'Cupertino', NULL),
    ('CA', 'Brentwood', NULL),
    ('CA', 'Petaluma', NULL),
    ('NJ', 'Vineland', NULL),
    ('UT', 'Taylorsville', NULL),
    ('ID', 'Idaho Falls', NULL),
    ('IN', 'Noblesville', NULL),
    ('CT', 'Bristol', NULL),
    ('WI', 'West Allis', NULL),
    ('CA', 'Gardena', NULL),
    ('CA', 'La Mesa', NULL),
    ('MI', 'St. Clair Shores', NULL),
    ('MI', 'Pontiac', NULL),
    ('CT', 'Meriden', NULL),
    ('CA', 'Dublin', NULL),
    ('FL', 'Coconut Creek', NULL),
    ('WY', 'Casper', NULL),
    ('KY', 'Owensboro', NULL),
    ('FL', 'Ocala', NULL),
    ('NC', 'Chapel Hill', NULL),
    ('TX', 'Pflugerville', NULL),
    ('PA', 'Lancaster', NULL),
    ('MI', 'Novi', NULL),
    ('MT', 'Great Falls', NULL),
    ('OH', 'Springfield', NULL),
    ('CA', 'Woodland', NULL),
    ('MI', 'Royal Oak', NULL),
    ('CA', 'Porterville', NULL),
    ('CA', 'San Rafael', NULL),
    ('CA', 'Huntington Park', NULL),
    ('IL', 'Orland Park', NULL),
    ('TN', 'Bartlett', NULL),
    ('FL', 'Sanford', NULL),
    ('IA', 'Dubuque', NULL),
    ('CA', 'Arcadia', NULL),
    ('MD', 'Bowie', NULL),
    ('NY', 'White Plains', NULL),
    ('IL', 'Des Plaines', NULL),
    ('FL', 'Doral', NULL),
    ('FL', 'Margate', NULL),
    ('CA', 'Santee', NULL),
    ('IN', 'Kokomo', NULL),
    ('CO', 'Castle Rock', NULL),
    ('ND', 'Grand Forks', NULL),
    ('OK', 'Midwest City', NULL),
    ('MO', 'St. Peters', NULL),
    ('MA', 'Medford', NULL),
    ('OR', 'Corvallis', NULL),
    ('TN', 'Hendersonville', NULL),
    ('NJ', 'New Brunswick', NULL),
    ('MA', 'Taunton', NULL),
    ('IL', 'Tinley Park', NULL),
    ('CA', 'Diamond Bar', NULL),
    ('GA', 'Smyrna', NULL),
    ('FL', 'Sarasota', NULL),
    ('IN', 'Greenwood', NULL),
    ('CA', 'Fountain Valley', NULL),
    ('GA', 'Valdosta', NULL),
    ('IL', 'Oak Lawn', NULL),
    ('CA', 'Novato', NULL),
    ('MA', 'Chicopee', NULL),
    ('MA', 'Weymouth Town', NULL),
    ('MI', 'Dearborn Heights', NULL),
    ('IL', 'Berwyn', NULL),
    ('FL', 'Bradenton', NULL),
    ('NY', 'Hempstead', NULL),
    ('CA', 'Hanford', NULL),
    ('NC', 'Rocky Mount', NULL),
    ('TX', 'Port Arthur', NULL),
    ('WA', 'Shoreline', NULL),
    ('OH', 'Kettering', NULL),
    ('IN', 'Anderson', NULL),
    ('AL', 'Decatur', NULL),
    ('CA', 'Gilroy', NULL),
    ('WA', 'Richland', NULL),
    ('KS', 'Manhattan', NULL),
    ('CA', 'Highland', NULL),
    ('CA', 'Paramount', NULL),
    ('CO', 'Commerce City', NULL),
    ('NC', 'Huntersville', NULL),
    ('TX', 'Euless', NULL),
    ('ID', 'Pocatello', NULL),
    ('NV', 'Carson City', NULL),
    ('CA', 'Colton', NULL),
    ('AZ', 'Casa Grande', NULL),
    ('CT', 'West Haven', NULL),
    ('CA', 'Rosemead', NULL),
    ('MO', 'Blue Springs', NULL),
    ('NJ', 'Hoboken', NULL),
    ('IL', 'Normal', NULL),
    ('FL', 'Bonita Springs', NULL),
    ('IL', 'Mount Prospect', NULL),
    ('CA', 'Cathedral City', NULL),
    ('CA', 'Watsonville', NULL),
    ('FL', 'Pensacola', NULL),
    ('FL', 'Palm Beach Gardens', NULL),
    ('AZ', 'Lake Havasu City', NULL),
    ('OH', 'Elyria', NULL),
    ('NE', 'Bellevue', NULL),
    ('IL', 'Wheaton', NULL),
    ('NJ', 'West New York', NULL),
    ('CA', 'Yucaipa', NULL),
    ('MS', 'Southaven', NULL),
    ('OR', 'Albany', NULL),
    ('MA', 'Revere', NULL),
    ('ID', 'Caldwell', NULL),
    ('VA', 'Harrisonburg', NULL),
    ('CA', 'West Sacramento', NULL),
    ('KS', 'Lenexa', NULL),
    ('TN', 'Kingsport', NULL),
    ('NC', 'Burlington', NULL),
    ('CA', 'Delano', NULL),
    ('VA', 'Leesburg', NULL),
    ('TX', 'DeSoto', NULL),
    ('CT', 'Milford', NULL),
    ('NJ', 'Perth Amboy', NULL),
    ('MA', 'Peabody', NULL),
    ('GA', 'Brookhaven', NULL),
    ('MN', 'Minnetonka', NULL),
    ('CA', 'Palm Desert', NULL),
    ('CA', 'Placentia', NULL),
    ('IN', 'Elkhart', NULL),
    ('MO', 'Joplin', NULL),
    ('FL', 'Pinellas Park', NULL),
    ('WI', 'La Crosse', NULL),
    ('TX', 'Grapevine', NULL),
    ('MN', 'Apple Valley', NULL),
    ('OR', 'Tigard', NULL),
    ('CA', 'Glendora', NULL),
    ('MO', 'Florissant', NULL),
    ('IL', 'Oak Park', NULL),
    ('IL', 'Hoffman Estates', NULL),
    ('MI', 'Kentwood', NULL),
    ('MI', 'Battle Creek', NULL),
    ('NE', 'Grand Island', NULL),
    ('CA', 'Aliso Viejo', NULL),
    ('MN', 'Edina', NULL),
    ('WA', 'Olympia', NULL),
    ('CO', 'Parker', NULL),
    ('OK', 'Enid', NULL),
    ('WA', 'Burien', NULL),
    ('FL', 'Coral Gables', NULL),
    ('UT', 'Logan', NULL),
    ('NJ', 'Plainfield', NULL),
    ('CA', 'Cerritos', NULL),
    ('TX', 'Galveston', NULL),
    ('ID', 'Coeur d''Alene', NULL),
    ('OH', 'Lakewood', NULL),
    ('CA', 'Poway', NULL),
    ('MA', 'Methuen', NULL),
    ('NY', 'Troy', NULL),
    ('CA', 'Azusa', NULL),
    ('NC', 'Wilson', NULL),
    ('TX', 'Bedford', NULL),
    ('OK', 'Stillwater', NULL),
    ('IL', 'Downers Grove', NULL),
    ('FL', 'Apopka', NULL),
    ('SC', 'Summerville', NULL),
    ('LA', 'Monroe', NULL),
    ('UT', 'Murray', NULL),
    ('CA', 'La Mirada', NULL),
    ('OH', 'Cuyahoga Falls', NULL),
    ('TN', 'Collierville', NULL),
    ('WV', 'Charleston', NULL),
    ('OH', 'Newark', NULL),
    ('MI', 'Saginaw', NULL),
    ('CA', 'Rancho Santa Margarita', NULL),
    ('CA', 'Cypress', NULL),
    ('PA', 'Harrisburg', NULL),
    ('GA', 'Dunwoody', NULL),
    ('MI', 'East Lansing', NULL),
    ('OH', 'Middletown', NULL),
    ('MN', 'St. Louis Park', NULL),
    ('ND', 'Minot', NULL),
    ('WI', 'Sheboygan', NULL),
    ('IN', 'Mishawaka', NULL),
    ('NY', 'Niagara Falls', NULL),
    ('TN', 'Smyrna', NULL),
    ('CA', 'Covina', NULL),
    ('MI', 'Portage', NULL),
    ('TX', 'Cedar Hill', NULL),
    ('CA', 'Ceres', NULL),
    ('TX', 'Texas City', NULL),
    ('ID', 'Twin Falls', NULL),
    ('NM', 'Roswell', NULL),
    ('WV', 'Huntington', NULL),
    ('AL', 'Madison', NULL),
    ('WI', 'Wauwatosa', NULL),
    ('IN', 'Lawrence', NULL),
    ('NC', 'Kannapolis', NULL),
    ('LA', 'Alexandria', NULL),
    ('FL', 'St. Cloud', NULL),
    ('TX', 'Wylie', NULL),
    ('CA', 'Palm Springs', NULL),
    ('WA', 'Lacey', NULL),
    ('MO', 'Chesterfield', NULL),
    ('MI', 'Roseville', NULL),
    ('CA', 'San Luis Obispo', NULL),
    ('IL', 'Glenview', NULL),
    ('CA', 'San Jacinto', NULL),
    ('OH', 'Euclid', NULL),
    ('NC', 'Apex', NULL),
    ('RI', 'East Providence', NULL),
    ('KS', 'Salina', NULL),
    ('UT', 'Draper', NULL),
    ('IN', 'Jeffersonville', NULL),
    ('AR', 'Bentonville', NULL),
    ('CA', 'Lincoln', NULL),
    ('MS', 'Hattiesburg', NULL),
    ('VA', 'Charlottesville', NULL),
    ('AZ', 'Maricopa', NULL),
    ('IN', 'Columbus', NULL),
    ('OH', 'Mentor', NULL),
    ('OH', 'Mansfield', NULL),
    ('TX', 'Keller', NULL),
    ('CT', 'Middletown', NULL),
    ('IL', 'Elmhurst', NULL),
    ('OH', 'Beavercreek', NULL),
    ('MA', 'Everett', NULL),
    ('CO', 'Littleton', NULL),
    ('FL', 'Titusville', NULL),
    ('MS', 'Biloxi', NULL),
    ('IN', 'West Lafayette', NULL),
    ('CA', 'Newark', NULL),
    ('NY', 'Binghamton', NULL),
    ('OH', 'Dublin', NULL),
    ('CA', 'Beaumont', NULL),
    ('FL', 'Fort Pierce', NULL),
    ('MT', 'Bozeman', NULL),
    ('VA', 'Blacksburg', NULL),
    ('TX', 'Burleson', NULL),
    ('CA', 'Coachella', NULL),
    ('NJ', 'Sayreville', NULL),
    ('FL', 'Ocoee', NULL),
    ('NJ', 'Hackensack', NULL),
    ('FL', 'Cutler Bay', NULL),
    ('OH', 'Cleveland Heights', NULL),
    ('OH', 'Strongsville', NULL),
    ('CA', 'Danville', NULL),
    ('PA', 'Altoona', NULL),
    ('WA', 'Bothell', NULL),
    ('MA', 'Attleboro', NULL),
    ('TX', 'Haltom City', NULL),
    ('FL', 'Oakland Park', NULL),
    ('TN', 'Cleveland', NULL),
    ('MA', 'Barnstable Town', NULL),
    ('CA', 'El Centro', NULL),
    ('CA', 'Morgan Hill', NULL),
    ('FL', 'North Miami Beach', NULL),
    ('PA', 'York', NULL),
    ('AR', 'Pine Bluff', NULL),
    ('IL', 'Lombard', NULL),
    ('AZ', 'Oro Valley', NULL),
    ('CA', 'Lompoc', NULL),
    ('FL', 'North Lauderdale', NULL),
    ('TX', 'Rockwall', NULL),
    ('FL', 'Altamonte Springs', NULL),
    ('AZ', 'Marana', NULL),
    ('NY', 'Freeport', NULL),
    ('AZ', 'Sierra Vista', NULL),
    ('IL', 'DeKalb', NULL),
    ('AZ', 'Prescott Valley', NULL),
    ('MA', 'Salem', NULL),
    ('IA', 'Urbandale', NULL),
    ('MO', 'Jefferson City', NULL),
    ('CA', 'San Bruno', NULL),
    ('WI', 'Fond du Lac', NULL),
    ('IL', 'Plainfield', NULL),
    ('NH', 'Concord', NULL),
    ('MA', 'Pittsfield', NULL),
    ('UT', 'Riverton', NULL),
    ('CA', 'Bell Gardens', NULL),
    ('GA', 'Peachtree Corners', NULL),
    ('TX', 'Leander', NULL),
    ('CA', 'Rohnert Park', NULL),
    ('OH', 'Fairfield', NULL),
    ('TN', 'Brentwood', NULL),
    ('AZ', 'Prescott', NULL),
    ('TX', 'Little Elm', NULL),
    ('MN', 'Moorhead', NULL),
    ('CA', 'Brea', NULL),
    ('NJ', 'Linden', NULL),
    ('CA', 'Rancho Palos Verdes', NULL),
    ('TX', 'The Colony', NULL),
    ('VT', 'Burlington', NULL),
    ('IL', 'Moline', NULL),
    ('FL', 'Ormond Beach', NULL),
    ('NJ', 'Kearny', NULL),
    ('MI', 'Midland', NULL),
    ('SC', 'Goose Creek', NULL),
    ('IL', 'Urbana', NULL),
    ('PA', 'State College', NULL),
    ('FL', 'Winter Garden', NULL),
    ('IL', 'Belleville', NULL),
    ('VA', 'Danville', NULL),
    ('WA', 'Edmonds', NULL),
    ('MN', 'Mankato', NULL),
    ('MA', 'Leominster', NULL),
    ('NM', 'Farmington', NULL),
    ('TX', 'Sherman', NULL),
    ('MA', 'Westfield', NULL),
    ('VA', 'Manassas', NULL),
    ('OH', 'Findlay', NULL),
    ('RI', 'Woonsocket', NULL),
    ('IA', 'Cedar Falls', NULL),
    ('MA', 'Beverly', NULL),
    ('TX', 'Coppell', NULL),
    ('IL', 'Buffalo Grove', NULL),
    ('CT', 'Shelton', NULL),
    ('KS', 'Hutchinson', NULL),
    ('TX', 'Huntsville', NULL),
    ('IL', 'Bartlett', NULL),
    ('CA', 'La Quinta', NULL),
    ('CA', 'Campbell', NULL),
    ('KY', 'Covington', NULL),
    ('SC', 'Sumter', NULL),
    ('WA', 'Bremerton', NULL),
    ('WA', 'Puyallup', NULL),
    ('CA', 'Oakley', NULL),
    ('MN', 'Shakopee', NULL),
    ('PA', 'Wilkes-Barre', NULL),
    ('NC', 'Hickory', NULL),
    ('IL', 'Quincy', NULL),
    ('SC', 'Hilton Head Island', NULL),
    ('MD', 'Hagerstown', NULL),
    ('MA', 'Fitchburg', NULL),
    ('CA', 'San Gabriel', NULL),
    ('CA', 'La Puente', NULL),
    ('IL', 'Crystal Lake', NULL),
    ('MA', 'Holyoke', NULL),
    ('CA', 'Calexico', NULL),
    ('IL', 'Streamwood', NULL),
    ('MN', 'Maplewood', NULL),
    ('NC', 'Wake Forest', NULL),
    ('IL', 'Carol Stream', NULL),
    ('TX', 'Weslaco', NULL),
    ('FL', 'Greenacres', NULL),
    ('GA', 'Gainesville', NULL),
    ('AZ', 'Bullhead City', NULL),
    ('AL', 'Florence', NULL),
    ('AZ', 'Apache Junction', NULL),
    ('OH', 'Warren', NULL),
    ('OH', 'Lancaster', NULL),
    ('WI', 'New Berlin', NULL),
    ('OH', 'Grove City', NULL),
    ('IL', 'Romeoville', NULL),
    ('MA', 'Chelsea', NULL),
    ('MA', 'Marlborough', NULL),
    ('MO', 'Cape Girardeau', NULL),
    ('CT', 'Norwich', NULL),
    ('FL', 'Hallandale Beach', NULL),
    ('TX', 'Duncanville', NULL),
    ('TX', 'Schertz', NULL),
    ('MA', 'Woburn', NULL),
    ('MD', 'Annapolis', NULL),
    ('TX', 'Friendswood', NULL),
    ('NM', 'Clovis', NULL),
    ('CA', 'Culver City', NULL),
    ('FL', 'Oviedo', NULL),
    ('TX', 'Hurst', NULL),
    ('MS', 'Meridian', NULL),
    ('CA', 'Pacifica', NULL),
    ('TN', 'Germantown', NULL),
    ('OH', 'Westerville', NULL),
    ('CO', 'Northglenn', NULL),
    ('OR', 'Keizer', NULL),
    ('FL', 'Winter Haven', NULL),
    ('OR', 'Lake Oswego', NULL),
    ('CA', 'Montclair', NULL),
    ('WI', 'Wausau', NULL),
    ('TX', 'Lancaster', NULL),
    ('UT', 'Spanish Fork', NULL),
    ('MS', 'Tupelo', NULL),
    ('UT', 'Pleasant Grove', NULL),
    ('NJ', 'Atlantic City', NULL),
    ('CA', 'Stanton', NULL),
    ('OH', 'Delaware', NULL),
    ('IA', 'Marion', NULL),
    ('GA', 'Milton', NULL),
    ('OK', 'Muskogee', NULL),
    ('MI', 'Muskegon', NULL),
    ('SC', 'Florence', NULL),
    ('IL', 'Wheeling', NULL),
    ('CO', 'Brighton', NULL),
    ('IL', 'Carpentersville', NULL),
    ('CA', 'Martinez', NULL),
    ('NC', 'Indian Trail', NULL),
    ('IL', 'Rock Island', NULL),
    ('UT', 'Roy', NULL),
    ('FL', 'Plant City', NULL);